
* ap-cgeng.fritz.box

** install.sh
*** install nvidia toolkit
see https://askubuntu.com/questions/128524/how-to-list-dependent-packages-reverse-dependencies for rdepends keyword
#+begin_src bash
apt-cache rdepends packagename nvidia-cuda-toolkit
#+end_src

#+RESULTS:
| nvidia-cuda-toolkit     |          |
| Reverse                 | Depends: |
| nvidia-cuda-toolkit-gcc |          |
| python3-pycuda          |          |
| nvidia-profiler         |          |
| hxtools                 |          |
| libthrust-dev           |          |
| python3-theano          |          |
| python3-numba           |          |
| nvptx-tools             |          |


#+begin_src  bash :results output raw
 sudo  apt install -y nvidia-cuda-toolkit
#+end_src


#+RESULTS:
sudo  apt install -y nvidia-cuda-toolkit
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  cpp-8 g++-8 gcc-8 gcc-8-base libaccinj64-10.1 libcublas10 libcublaslt10 libcudart10.1 libcufft10 libcufftw10 libcuinj64-10.1 libcupti-dev libcupti-doc libcupti10.1 libcurand10 libcusolver10
  libcusolvermg10 libcusparse10 libgcc-8-dev libmpx2 libncurses5 libnppc10 libnppial10 libnppicc10 libnppicom10 libnppidei10 libnppif10 libnppig10 libnppim10 libnppist10 libnppisu10 libnppitc10
  libnpps10 libnvblas10 libnvgraph10 libnvidia-ml-dev libnvjpeg10 libnvrtc10.1 libnvtoolsext1 libnvvm3 libstdc++-8-dev libthrust-dev libtinfo5 libvdpau-dev node-html5shiv nsight-compute nsight-systems
  nvidia-cuda-dev nvidia-cuda-doc nvidia-cuda-gdb nvidia-opencl-dev nvidia-profiler nvidia-visual-profiler ocl-icd-opencl-dev opencl-c-headers openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  gcc-8-locales g++-8-multilib gcc-8-doc gcc-8-multilib libstdc++-8-doc libvdpau-doc nodejs nvidia-driver | nvidia-tesla-440-driver | nvidia-tesla-418-driver libpoclu-dev fonts-ipafont-gothic
  fonts-ipafont-mincho fonts-wqy-microhei fonts-wqy-zenhei
Recommended packages:
  libnvcuvid1
The following NEW packages will be installed:
  cpp-8 g++-8 gcc-8 gcc-8-base libaccinj64-10.1 libcublas10 libcublaslt10 libcudart10.1 libcufft10 libcufftw10 libcuinj64-10.1 libcupti-dev libcupti-doc libcupti10.1 libcurand10 libcusolver10
  libcusolvermg10 libcusparse10 libgcc-8-dev libmpx2 libncurses5 libnppc10 libnppial10 libnppicc10 libnppicom10 libnppidei10 libnppif10 libnppig10 libnppim10 libnppist10 libnppisu10 libnppitc10
  libnpps10 libnvblas10 libnvgraph10 libnvidia-ml-dev libnvjpeg10 libnvrtc10.1 libnvtoolsext1 libnvvm3 libstdc++-8-dev libthrust-dev libtinfo5 libvdpau-dev node-html5shiv nsight-compute nsight-systems
  nvidia-cuda-dev nvidia-cuda-doc nvidia-cuda-gdb nvidia-cuda-toolkit nvidia-opencl-dev nvidia-profiler nvidia-visual-profiler ocl-icd-opencl-dev opencl-c-headers openjdk-8-jre openjdk-8-jre-headless
0 upgraded, 58 newly installed, 0 to remove and 15 not upgraded.
Need to get 1.355 MB/1.428 MB of archives.
After this operation, 3.819 MB of additional disk space will be used.


*** Check cuda version

#+begin_src  bash :results output pp
nvcc --version
#+end_src

#+RESULTS:
: nvcc: NVIDIA (R) Cuda compiler driver
: Copyright (c) 2005-2019 NVIDIA Corporation
: Built on Sun_Jul_28_19:07:16_PDT_2019
: Cuda compilation tools, release 10.1, V10.1.243

see
https://linuxconfig.org/how-to-install-cuda-on-ubuntu-20-04-focal-fossa-linux


*** Compile a Sample CUDA code

#+begin_example c
#include <stdio.h>

__global__
void saxpy(int n, float a, float *x, float *y)
{
  int i = blockIdx.x*blockDim.x + threadIdx.x;
  if (i < n) y[i] = a*x[i] + y[i];
}

int main(void)
{
  int N = 1<<20;
  float *x, *y, *d_x, *d_y;
  x = (float*)malloc(N*sizeof(float));
  y = (float*)malloc(N*sizeof(float));

  cudaMalloc(&d_x, N*sizeof(float));
  cudaMalloc(&d_y, N*sizeof(float));

  for (int i = 0; i < N; i++) {
    x[i] = 1.0f;
    y[i] = 2.0f;
  }

  cudaMemcpy(d_x, x, N*sizeof(float), cudaMemcpyHostToDevice);
  cudaMemcpy(d_y, y, N*sizeof(float), cudaMemcpyHostToDevice);

  // Perform SAXPY on 1M elements
  saxpy<<<(N+255)/256, 256>>>(N, 2.0f, d_x, d_y);

  cudaMemcpy(y, d_y, N*sizeof(float), cudaMemcpyDeviceToHost);

  float maxError = 0.0f;
  for (int i = 0; i < N; i++)
    maxError = max(maxError, abs(y[i]-4.0f));
  printf("Max error: %f\n", maxError);

  cudaFree(d_x);
  cudaFree(d_y);
  free(x);
  free(y);
}
#+end_example

$ nvcc -o hello hello.cu
$ ./hello
Max error: 0.000000


*** Chose compiler

#+begin_exampple bash
history | grep alternatives | grep -v   "#"
#+end_example

#+RESULTS:
2013  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
2014  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
2017  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
2018  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
2020  sudo update-alternatives --config gcc
2021  sudo update-alternatives --config g++







** Data

- All fork off from =run.sh=

*** local/main_download_data.sh

**** Libri and vctk dev and test sets

- local/download_data is a paraemetrized script that does ftp access and download:
- File: baseline/config.sh contains the below configurations:

#+begin_src shell
  ##########################################################
  # Evaluation data sets
  eval_sets='libri vctk'
  eval_subsets='dev test'

  for dset in $eval_sets ; do
    for suff in $eval_subsets; do
        echo "${dset}_${suff}.tar.gz"
        tar -ztvf baseline/${dset}_${suff}.tar.gz  | head -n 15
    done
  done

#+end_src

#+RESULTS:
| libri_dev.tar.gz  |                      |        |            |       |                                                          |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-06 | 22:03 | data/                                                    |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-06 | 22:02 | data/libri_dev/                                          |
| -rw-r-----        | ntomashenko/laboinfo |  49305 | 2020-02-06 | 22:01 | data/libri_dev/utt2spk                                   |
| -rw-r-----        | ntomashenko/laboinfo | 671086 | 2014-08-17 | 08:45 | data/libri_dev/CHAPTERS.TXT                              |
| -rw-r-----        | ntomashenko/laboinfo |   5614 | 2020-02-06 | 21:32 | data/libri_dev/enrolls                                   |
| -rw-r-----        | ntomashenko/laboinfo | 115746 | 2014-10-03 | 13:15 | data/libri_dev/BOOKS.TXT                                 |
| -rw-r-----        | ntomashenko/laboinfo | 478297 | 2020-02-04 | 19:57 | data/libri_dev/trials_f                                  |
| -rw-r-----        | ntomashenko/laboinfo |    273 | 2020-02-06 | 22:01 | data/libri_dev/spk2gender                                |
| -rw-r-----        | ntomashenko/laboinfo |   8039 | 2014-10-03 | 13:12 | data/libri_dev/README.TXT                                |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-06 | 21:47 | data/libri_dev/wav/                                      |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-06 | 21:47 | data/libri_dev/wav/84-121123-0022/                       |
| -rw-r-----        | ntomashenko/laboinfo |  83564 | 2020-02-06 | 21:47 | data/libri_dev/wav/84-121123-0022/84-121123-0022.wav     |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-06 | 21:45 | data/libri_dev/wav/2078-142845-0008/                     |
| -rw-r-----        | ntomashenko/laboinfo | 620204 | 2020-02-06 | 21:45 | data/libri_dev/wav/2078-142845-0008/2078-142845-0008.wav |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-06 | 21:46 | data/libri_dev/wav/6313-66125-0023/                      |
| libri_test.tar.gz |                      |        |            |       |                                                          |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-16 | 17:18 | data/libri_test/                                         |
| -rw-r-----        | ntomashenko/laboinfo |  54512 | 2020-02-16 | 17:18 | data/libri_test/utt2spk                                  |
| -rw-r-----        | ntomashenko/laboinfo | 671086 | 2014-08-17 | 08:45 | data/libri_test/CHAPTERS.TXT                             |
| -rw-r-----        | ntomashenko/laboinfo |   6951 | 2020-02-15 | 20:57 | data/libri_test/enrolls                                  |
| -rw-r-----        | ntomashenko/laboinfo | 115746 | 2014-10-03 | 13:15 | data/libri_test/BOOKS.TXT                                |
| -rw-r-----        | ntomashenko/laboinfo | 361032 | 2020-02-15 | 21:05 | data/libri_test/trials_f                                 |
| -rw-r-----        | ntomashenko/laboinfo |    273 | 2020-02-16 | 17:18 | data/libri_test/spk2gender                               |
| -rw-r-----        | ntomashenko/laboinfo |   8039 | 2014-10-03 | 13:12 | data/libri_test/README.TXT                               |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-15 | 20:50 | data/libri_test/wav/                                     |
| -rw-r-----        | ntomashenko/laboinfo | 520364 | 2020-02-15 | 20:49 | data/libri_test/wav/2094-142345-0011.wav                 |
| -rw-r-----        | ntomashenko/laboinfo | 627564 | 2020-02-15 | 20:50 | data/libri_test/wav/4077-13751-0005.wav                  |
| -rw-r-----        | ntomashenko/laboinfo | 105804 | 2020-02-15 | 20:50 | data/libri_test/wav/6930-81414-0002.wav                  |
| -rw-r-----        | ntomashenko/laboinfo | 285804 | 2020-02-15 | 20:50 | data/libri_test/wav/7729-102255-0019.wav                 |
| -rw-r-----        | ntomashenko/laboinfo | 327724 | 2020-02-15 | 20:50 | data/libri_test/wav/908-157963-0021.wav                  |
| -rw-r-----        | ntomashenko/laboinfo |  62604 | 2020-02-15 | 20:49 | data/libri_test/wav/1995-1837-0008.wav                   |
| vctk_dev.tar.gz   |                      |        |            |       |                                                          |
| drwxrwxr-x        | 1002/ntomashenko     |      0 | 2020-02-05 | 21:24 | data/                                                    |
| drwxr-x---        | 1002/ntomashenko     |      0 | 2020-02-02 | 17:52 | data/vctk_dev/                                           |
| -rw-r-----        | 1002/ntomashenko     | 232807 | 2020-01-26 | 23:20 | data/vctk_dev/utt2spk                                    |
| -rw-r-----        | 1002/ntomashenko     |  17416 | 2019-12-10 | 14:33 | data/vctk_dev/license_text                               |
| -rw-r-----        | 1002/ntomashenko     |    425 | 2020-02-02 | 17:47 | data/vctk_dev/README_vctk_dev.txt                        |
| -rw-r-----        | 1002/ntomashenko     | 151545 | 2020-02-05 | 19:32 | data/vctk_dev/trials_m_common_mic2                       |
| -rw-r-----        | 1002/ntomashenko     | 429657 | 2020-02-05 | 19:32 | data/vctk_dev/trials_f_mic2                              |
| -rw-r-----        | 1002/ntomashenko     | 288392 | 2020-01-26 | 23:20 | data/vctk_dev/utt2dur                                    |
| -rw-r-----        | 1002/ntomashenko     |    240 | 2019-12-27 | 19:26 | data/vctk_dev/utt2num_mic2.ark                           |
| -rw-r-----        | 1002/ntomashenko     | 676506 | 2020-01-26 | 23:20 | data/vctk_dev/text                                       |
| -rw-r-----        | 1002/ntomashenko     | 171692 | 2020-01-26 | 23:20 | data/vctk_dev/spk2utt                                    |
| -rw-r-----        | 1002/ntomashenko     |    210 | 2020-01-26 | 23:20 | data/vctk_dev/spk2gender                                 |
| -rw-r-----        | 1002/ntomashenko     | 148434 | 2020-02-05 | 19:32 | data/vctk_dev/trials_f_common_mic2                       |
| -rw-r-----        | 1002/ntomashenko     |   8400 | 2020-02-05 | 19:31 | data/vctk_dev/enrolls_mic2                               |
| -rw-r-----        | 1002/ntomashenko     |   5236 | 2019-12-10 | 14:33 | data/vctk_dev/README.txt                                 |
| vctk_test.tar.gz  |                      |        |            |       |                                                          |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-16 | 01:13 | data/vctk_test/                                          |
| -rw-r-----        | ntomashenko/laboinfo | 152812 | 2020-02-05 | 19:32 | data/vctk_test/trials_m_common_mic2                      |
| -rw-r-----        | ntomashenko/laboinfo | 234650 | 2020-02-15 | 23:31 | data/vctk_test/utt2spk                                   |
| -rw-r-----        | ntomashenko/laboinfo |   5236 | 2019-12-10 | 14:33 | data/vctk_test/README.txt                                |
| -rw-r-----        | ntomashenko/laboinfo | 149298 | 2020-02-05 | 19:32 | data/vctk_test/trials_f_common_mic2                      |
| -rw-r-----        | ntomashenko/laboinfo |   8400 | 2020-02-05 | 19:31 | data/vctk_test/enrolls_mic2                              |
| -rw-r-----        | ntomashenko/laboinfo |    486 | 2020-02-16 | 01:13 | data/vctk_test/README_vctk_test.txt                      |
| -rw-r-----        | ntomashenko/laboinfo | 429168 | 2020-02-05 | 19:32 | data/vctk_test/trials_f_mic2                             |
| -rw-r-----        | ntomashenko/laboinfo |    210 | 2020-02-15 | 23:31 | data/vctk_test/spk2gender                                |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-02-15 | 18:58 | data/vctk_test/wav/                                      |
| drwxr-x---        | ntomashenko/laboinfo |      0 | 2020-01-27 | 02:27 | data/vctk_test/wav/p270/                                 |
| -rw-r-----        | ntomashenko/laboinfo |  63108 | 2020-01-27 | 02:26 | data/vctk_test/wav/p270/p270_382_mic2.wav                |
| -rw-r-----        | ntomashenko/laboinfo | 108062 | 2020-01-27 | 02:26 | data/vctk_test/wav/p270/p270_384_mic2.wav                |
| -rw-r-----        | ntomashenko/laboinfo | 126236 | 2020-01-27 | 02:26 | data/vctk_test/wav/p270/p270_329_mic2.wav                |
| -rw-r-----        | ntomashenko/laboinfo | 103800 | 2020-01-27 | 02:26 | data/vctk_test/wav/p270/p270_100_mic2.wav                |







**** train-clean-360-spk

- the data directory contains metadata to link speakers to sex and utterances to speaker


#+begin_src bash :results output pp
ls baseline -lt
#+end_src

#+RESULTS:
#+begin_example
total 1090736
-rw-r--r--  1 cgeng domain users 177192960 Feb  5 19:08 vctk_dev.tar.gz
-rw-r--r--  1 cgeng domain users 510067307 Feb  5 19:07 libri_test.tar.gz
-rw-r--r--  1 cgeng domain users 429558361 Feb  5 19:02 libri_dev.tar.gz
drwxr-xr-x  2 cgeng domain users      4096 Feb  3 16:35 corpora
-rwxr-xr-x  1 cgeng domain users      5993 Feb  1 12:37 run.sh
-rwxr-xr-x  1 cgeng domain users      2622 Feb  1 12:37 run_tts_train.sh
-rwxr-xr-x  1 cgeng domain users      5834 Feb  1 12:37 run_xvector.sh
lrwxrwxrwx  1 cgeng domain users        25 Feb  1 12:37 sid -> ../kaldi/egs/sre08/v1/sid
lrwxrwxrwx  1 cgeng domain users        25 Feb  1 12:37 steps -> ../kaldi/egs/wsj/s5/steps
lrwxrwxrwx  1 cgeng domain users        25 Feb  1 12:37 utils -> ../kaldi/egs/wsj/s5/utils
lrwxrwxrwx  1 cgeng domain users        33 Feb  1 12:37 local_librispeech -> ../kaldi/egs/librispeech/s5/local
-rw-r--r--  1 cgeng domain users       500 Feb  1 12:37 path.sh
-rwxr-xr-x  1 cgeng domain users     10924 Feb  1 12:37 print_config.sh
drwxr-xr-x  2 cgeng domain users      4096 Feb  1 12:37 results
drwxr-xr-x  2 cgeng domain users      4096 Feb  1 12:37 results_old
drwxr-xr-x 10 cgeng domain users      4096 Feb  1 12:37 local
drwxr-xr-x  2 cgeng domain users      4096 Feb  1 12:37 fig
drwxr-xr-x  2 cgeng domain users      4096 Feb  1 12:37 conf
-rw-r--r--  1 cgeng domain users      7818 Feb  1 12:37 config.sh
-rwxr-xr-x  1 cgeng domain users      6205 Feb  1 12:37 cleanup.sh
-rw-r--r--  1 cgeng domain users       917 Feb  1 12:37 cmd.sh
#+end_example

Get the data from compute3.

#+begin_src shell :results output pp
    mkdir -p  baseline/data/train-clean-360-spk
    # rsync -aPqi compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/data/train-clean-360-spk/  baseline/data/train-clean-360-spk/
    ls -l  baseline/data/train-clean-360-spk/
    tar -ztvf   baseline/data/train-clean-360-spk/train-clean-360-spk.tar.gz | head -n 200
  pwd
#+end_src

#+RESULTS:
: total 228
: drwxr-x--- 2 cgeng domain users   4096 Dez 28  2021 train-clean-360-spk
: -rw-r--r-- 1 cgeng domain users 227600 Jan 26 16:14 train-clean-360-spk.tar.gz
: drwxr-x--- philou/taln       0 2021-12-28 13:04 train-clean-360-spk/
: -rw-r----- philou/taln 2199854 2021-12-28 04:52 train-clean-360-spk/utt2spk
: -rw-r----- philou/taln    6268 2021-12-28 04:52 train-clean-360-spk/spk2gender
: /home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box


meta of speaker data:

#+begin_src shell :results output pp
head baseline/data/train-clean-360-spk/train-clean-360-spk/spk2gender
tail baseline/data/train-clean-360-spk/train-clean-360-spk/spk2gender
#+end_src

#+RESULTS:
#+begin_example
100 f
1001 m
101 m
1012 f
1018 m
1025 m
1027 m
1028 m
1031 f
1046 m
948 f
949 m
953 m
954 m
957 m
968 f
979 f
98 f
984 m
986 m
#+end_example


#+begin_src shell :results output pp
  head baseline/data/train-clean-360-spk/train-clean-360-spk/utt2spk
  tail baseline/data/train-clean-360-spk/train-clean-360-spk/utt2spk
#+end_src

#+RESULTS:
#+begin_example
100-121669-0000 100
100-121669-0001 100
100-121669-0002 100
100-121669-0003 100
100-121669-0004 100
100-121669-0005 100
100-121669-0006 100
100-121669-0007 100
100-121669-0008 100
100-121669-0009 100
986-129388-0103 986
986-129388-0104 986
986-129388-0105 986
986-129388-0106 986
986-129388-0107 986
986-129388-0108 986
986-129388-0109 986
986-129388-0110 986
986-129388-0111 986
986-129388-0112 986
#+end_example



**** Downloading F0 for train-clean-360-asv

expo=exp/am_nsf_data
mkdir -p  baseline/$expo
fname=train-clean-360-asv.tar.gz
rsync -aP compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/$expo/$fname baseline/$expo/$fname


#+begin_src bash :results output pp
  expo=exp/am_nsf_data
  mkdir -p  baseline/$expo
  fname=train-clean-360-asv.tar.gz
  tar -ztvf   baseline/$expo/$fname | head
  ls baseline/$expo/$fname
#+end_src

#+RESULTS:
#+begin_example
drwxr-x--- philou/taln       0 2022-01-10 15:26 train-clean-360-asv/
drwxr-x--- philou/taln       0 2022-01-02 10:53 train-clean-360-asv/f0/
-rw-r----- philou/taln    3064 2022-01-02 10:29 train-clean-360-asv/f0/6993-83606-0014.f0
-rw-r----- philou/taln    5112 2022-01-02 10:43 train-clean-360-asv/f0/8176-115046-0023.f0
-rw-r----- philou/taln    5796 2022-01-02 09:28 train-clean-360-asv/f0/3717-21498-0004.f0
-rw-r----- philou/taln    6416 2022-01-02 08:58 train-clean-360-asv/f0/208-126851-0016.f0
-rw-r----- philou/taln    5808 2022-01-02 09:47 train-clean-360-asv/f0/409-124990-0032.f0
-rw-r----- philou/taln    3492 2022-01-02 09:16 train-clean-360-asv/f0/318-124224-0012.f0
-rw-r----- philou/taln    6252 2022-01-02 10:34 train-clean-360-asv/f0/7525-101265-0007.f0
-rw-r----- philou/taln    5912 2022-01-02 09:47 train-clean-360-asv/f0/409-124990-0029.f0
baseline/exp/am_nsf_data/train-clean-360-asv.tar.gz
#+end_example



***   local/download_models.sh - download pretrained models

Das models tar liegt an der falschen Stelle, ich habe es nach  baseline/exp/
verschoben und mit tar xzf models.2022.tar.gz entpackt!

expo=exp/
models=models.2022.tar.gz
rsync -aP compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/$expo/$models baseline/$expo/$models

#+begin_src bash  : :results output pp
ls baseline/exp/models  -l
#+end_src

#+RESULTS:
#+begin_example
total 72
drwxr-x--- 4 cgeng domain users 4096 Jan 16  2020 1_asr_am
drwxr-x--- 4 cgeng domain users 4096 Jan 16  2020 2_xvect_extr
drwxr-x--- 2 cgeng domain users 4096 Dez 11  2021 2_xvect_extr_sidekit
drwxr-x--- 2 cgeng domain users 4096 Jan 21  2020 3_ss_am
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 3_ss_am_pt
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 3_ss_am_pt_sidekit
drwxr-x--- 2 cgeng domain users 4096 Jan 21  2020 4_nsf
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 4_nsf_pt
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 4_nsf_pt_sidekit
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 5_joint_tts_hifigan
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 5_joint_tts_hifigan_sidekit
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 5_joint_tts_nsf_hifigan
drwxr-x--- 2 cgeng domain users 4096 Feb 22  2022 5_joint_tts_nsf_hifigan_sidekit
drwxr-x--- 9 cgeng domain users 4096 Dez 29  2021 asr_eval
drwxr-x--- 7 cgeng domain users 4096 Nov 10  2020 asr_eval_b1_anon
drwxr-x--- 3 cgeng domain users 4096 Jan 27  2020 asv_eval
drwxr-x--- 3 cgeng domain users 4096 Nov 10  2020 asv_eval_b1_anon
drwxr-x--- 2 cgeng domain users 4096 Dez 11  2021 asv_eval_sidekit
#+end_example


*** LibriSpeech and LibriTTS datasets

Nach dem download solls so aussehen:

drwxr-xr-x  4 cgeng domain users 4.0K Jan 28 02:26 ./
drwxr-xr-x 11 cgeng domain users 4.0K Jan 28 08:44 ../
drwxr-xr-x  5 cgeng domain users 4.0K Jan 28 02:20 LibriSpeech/
drwxr-xr-x  4 cgeng domain users 4.0K Jan 27 03:11 LibriTTS/
-rw-r--r--  1 cgeng domain users 7.2G Apr  2  2019 train-clean-100.tar.gz
-rw-r--r--  1 cgeng domain users  42G Apr  2  2019 train-other-500.tar.gz

*** Download LibriSpeech data sets for training anonymization system (train-other-500, train-clean-100) - local/main_download_and_untar_libri.sh

libri_train_sets="$libri_train_clean_100 $libri_train_other_500"

**** local/main_download_and_untar_libri.sh

directory for corpora: corpora
download url: www.openslr.org/resources/12
PART: train-clean-100
directory for corpora: corpora
download url: www.openslr.org/resources/12
PART: train-other-500
  Done

**** Download corpora

***** train-clean-100
part=train-clean-100
corpora=corpora
data_url_librispeech=www.openslr.org/resources/12
# das löscht den tarball:
local/download_and_untar.sh --remove-archive $corpora $data_url_librispeech $part LibriSpeech
# das löscht ihn nicht
local/download_and_untar.sh  $corpora $data_url_librispeech $part LibriSpeech

So muss das aussehen:

pwd; ls   train-other-500.tar.gz
/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/corpora
train-other-500.tar.gz



#+begin_src bash :results output pp
part=train-clean-100
tar -ztvf baseline/corpora/$part.tar.gz | head -n 25
#+end_src

#+RESULTS:
#+begin_example
-rw-r--r-- vassil/vassil   193 2014-08-17 08:19 LibriSpeech/LICENSE.TXT
-rw-r--r-- vassil/vassil  8039 2014-10-03 13:12 LibriSpeech/README.TXT
-rw-r--r-- vassil/vassil 671086 2014-08-17 08:45 LibriSpeech/CHAPTERS.TXT
-rw-r--r-- vassil/vassil 125034 2014-08-17 08:45 LibriSpeech/SPEAKERS.TXT
-rw-r--r-- vassil/vassil 115746 2014-10-03 13:15 LibriSpeech/BOOKS.TXT
drwxr-xr-x vassil/vassil      0 2014-08-16 08:17 LibriSpeech/train-clean-100/
drwxr-xr-x vassil/vassil      0 2014-08-16 08:15 LibriSpeech/train-clean-100/374/
drwxr-xr-x vassil/vassil      0 2014-08-16 08:15 LibriSpeech/train-clean-100/374/180298/
-r--r--r-- vassil/vassil 228475 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0021.flac
-r--r--r-- vassil/vassil 152231 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0038.flac
-r--r--r-- vassil/vassil 260792 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0022.flac
-r--r--r-- vassil/vassil 254636 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0044.flac
-r--r--r-- vassil/vassil 225397 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0006.flac
-r--r--r-- vassil/vassil 253055 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0051.flac
-r--r--r-- vassil/vassil 150583 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0060.flac
-r--r--r-- vassil/vassil 264623 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0028.flac
-r--r--r-- vassil/vassil 187921 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0045.flac
-r--r--r-- vassil/vassil 231822 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0036.flac
-r--r--r-- vassil/vassil 224890 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0053.flac
-r--r--r-- vassil/vassil 246321 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0032.flac
-r--r--r-- vassil/vassil 290808 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0018.flac
-r--r--r-- vassil/vassil 288138 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0007.flac
-r--r--r-- vassil/vassil 178398 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0043.flac
-r--r--r-- vassil/vassil 256378 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0014.flac
-r--r--r-- vassil/vassil 237941 2014-07-08 11:13 LibriSpeech/train-clean-100/374/180298/374-180298-0049.flac
#+end_example

****** Log


local/download_and_untar.sh: Successfully downloaded and un-tarred corpora/train-clean-100.tar.gz
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$ #local/download_and_untar.sh  $corpora $data_url_librispeech $part LibriSpeech
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$ echo $part
train-clean-100
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$ echo $part  $data_url_librispeech    $corpora
train-clean-100 www.openslr.org/resources/12 corpora
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$




***** part=train-other-500

part=train-other-500
corpora=corpora
data_url_librispeech=www.openslr.org/resources/12
full_url=$data_url_librispeech/$part.tar.gz
local/download_and_untar.sh  $corpora $data_url_librispeech $part LibriSpeech


#+begin_src bash :results output pp
part=train-other-500
tar -ztvf baseline/corpora/$part.tar.gz | head
#+end_src

#+RESULTS:
#+begin_example
-rw-r--r-- vassil/vassil   193 2014-08-17 08:19 LibriSpeech/LICENSE.TXT
-rw-r--r-- vassil/vassil  8039 2014-10-03 13:12 LibriSpeech/README.TXT
-rw-r--r-- vassil/vassil 671086 2014-08-17 08:45 LibriSpeech/CHAPTERS.TXT
-rw-r--r-- vassil/vassil 125034 2014-08-17 08:45 LibriSpeech/SPEAKERS.TXT
-rw-r--r-- vassil/vassil 115746 2014-10-03 13:15 LibriSpeech/BOOKS.TXT
drwxr-xr-x vassil/vassil      0 2014-08-16 18:53 LibriSpeech/train-other-500/
drwxr-xr-x vassil/vassil      0 2014-08-16 16:26 LibriSpeech/train-other-500/8296/
drwxr-xr-x vassil/vassil      0 2014-08-16 16:26 LibriSpeech/train-other-500/8296/266250/
-r--r--r-- vassil/vassil 240201 2014-07-08 18:02 LibriSpeech/train-other-500/8296/266250/8296-266250-0012.flac
-r--r--r-- vassil/vassil 120419 2014-07-08 18:02 LibriSpeech/train-other-500/8296/266250/8296-266250-0004.flac
#+end_example











*** Download LibriTTS data sets for training anonymization system (train-other-500, train-clean-100) - local/main_download_and_untar_libritts.sh

Lediglich der data_url ist anders!

local/download_and_untar.sh
data_url=www.openslr.org/resources/60
part=train-clean-100
corpora=corpora

local/download_and_untar.sh --remove-archive $corpora $data_url $part LibriSpeech
# das löscht ihn nicht
local/download_and_untar.sh  $corpora $data_url $part LibriSpeech



-----
data_url=www.openslr.org/resources/60
part=train-other-500
corpora=corporatts




*** Prepare data for anonymization pool data (libritts-train-other-500) -     local/main_data_prep_libritts.sh


**** Call stack



# Note: C-c ' (org-edit~special) erlaubt es die Datei zu öffnen!
#+INCLUDE: "./baseline/local/main_data_prep_libritts.sh"
#+INCLUDE: "./baseline/local/data_prep_libritts.sh"


echo $libritts_corpus
das ist das input verzeichnis: libritts_corpus=$(realpath $corpora/LibriTTS)
/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/corpora/LibriTTS

Call: local/data_prep_libritts.sh ${libritts_corpus}/${libritts_train_other_500} data/${anoni_pool} || exit 1


also: ~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/corpora/LibriTTS/train-other-500/

nach ~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/

File: baseline/local/anon/anonymize_data_dir.sh
17:1:anoni_pool="libritts_train_other_500" # change this to the data you want to use for anonymization pool

**** Zusstand daten davor:

#+begin_src bash :results output pp
ls -l ~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/
#+end_src

#+RESULTS:
: total 4
: drwxr-xr-x 3 cgeng domain users 4096 Jan 26 16:14 train-clean-360-spk

**** Mein Ergebnis für isolierten call - was ich machen muss

cd baseline/
# config.sh defines this:  libritts_train_other_500=train-other-500
. ./config.sh
corpora=corpora
libritts_corpus=$(realpath $corpora/LibriTTS)
# das ist nirgends anders definiert sagt der silver searcher
# see baseline/config.sh or baseline/local/anon/anonymize_data_dir.sh (latter not relevant here)
anoni_pool="libritts_train_other_500"
local/data_prep_libritts.sh ${libritts_corpus}/${libritts_train_other_500} data/${anoni_pool}

**** Zusstand daten danach:

#+begin_src bash :results output pp
  ls -lh ~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/
  du -mah ~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/ --max-depth=1
#+end_src

#+RESULTS:
: total 8,0K
: drwxr-xr-x 2 cgeng domain users 4,0K Feb  6 12:09 libritts_train_other_500
: drwxr-xr-x 3 cgeng domain users 4,0K Jan 26 16:14 train-clean-360-spk
: 2,4M	/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/train-clean-360-spk
: 70M	/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/libritts_train_other_500
: 72M	/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/


Was wird erzeugt?
- wav.scp: sox log
- spk2gender und utt2spk: Die Mappings
- text: asr results?
- Zum schluss:

#+begin_src bash :results output pp
  ls -lh ~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/data/libritts_train_other_500
#+end_src

#+RESULTS:
: total 85M
: -rw-r--r-- 1 cgeng domain users 7,8K Feb  6 12:31 spk2gender
: -rw-r--r-- 1 cgeng domain users 5,9M Feb  6 12:31 spk2utt
: -rw-r--r-- 1 cgeng domain users  24M Feb  6 12:31 text
: -rw-r--r-- 1 cgeng domain users 6,9M Feb  6 12:31 utt2spk
: -rw-r--r-- 1 cgeng domain users  49M Feb  6 12:31 wav.scp


**** Log:

#+begin_example
local/data_prep_libritts.sh ${libritts_corpus}/${libritts_train_other_500} data/${anoni_pool}
fix_data_dir.sh: kept all 205044 utterances.
fix_data_dir.sh: old files are kept in data/libritts_train_other_500/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libritts_train_other_500
local/data_prep_libritts.sh: successfully prepared data in data/libritts_train_other_500
#+end_example

**** corporatts www.openslr.org/resources/60 train-clean-100 LibriSpeech


/LibriTTS/BOOKS.txt
./LibriTTS/CHAPTERS.txt
./LibriTTS/LICENSE.txt
./LibriTTS/NOTE.txt
./LibriTTS/README_librispeech.txt
./LibriTTS/README_libritts.txt
./LibriTTS/SPEAKERS.txt
LibriTTS/eval_sentences10.tsv
LibriTTS/reader_book.tsv
LibriTTS/speakers.tsv
touch: cannot touch 'corporatts/LibriSpeech/train-clean-100/.complete': No such file or directory
local/download_and_untar.sh: Successfully downloaded and un-tarred corporatts/train-clean-100.tar.gz
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$  echo $part  $data_url_librispeech    $corpora
train-clean-100 corporatts
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$ echo   $corpora $data_url $part LibriSpeech
corporatts www.openslr.org/resources/60 train-clean-100 LibriSpeech
cgeng@ap-cgeng:~/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$






**** corporatts www.openslr.org/resources/60 train-other-500 LibriSpeech

LibriTTS/eval_sentences10.tsv
LibriTTS/reader_book.tsv
LibriTTS/speakers.tsv
touch: cannot touch 'corporatts/LibriSpeech/train-other-500/.complete': No such file or directory
local/download_and_untar.sh: Successfully downloaded and un-tarred corporatts/train-other-500.tar.gz


*** Extract xvectors from anonymization pool local/main_extract_xvectors_pool.sh

**** Call Stack
#+INCLUDE: "./baseline/local/main_extract_xvectors_pool.sh"
#+INCLUDE: "./baseline/local/featex/01_extract_xvectors.sh"

parse options kommt von hier:

#+begin_src bash :results output pp
find   -iname parse_options.sh
#+end_src

#+RESULTS:
: ./kaldi/egs/wsj/s5/utils/parse_options.sh

**** Assemble call

# definiert
. ./config.sh

***** anoni_pool
# aus config.sh
anoni_pool=libritts_train_other_500

***** nj

# integer für die Anzahl Prozessoren:
nj=$(nproc)


***** # xvec_nnet_dir definiert in config.sh

Content dieses xvector nnet dirs

#+begin_src bash :results output pp
xvec_nnet_dir=exp/models/2_xvect_extr/exp/xvector_nnet_1a # x-vector extractor
ls baseline/$xvec_nnet_dir/ -l
#+end_src

#+RESULTS:
#+begin_example
total 33076
-rw-r----- 1 cgeng domain users     2389 Dez  8  2019 accuracy.output.report
drwxr-x--- 2 cgeng domain users     4096 Jan 30  2020 anon
drwxr-x--- 2 cgeng domain users     4096 Dez  8  2019 configs
-rw-r----- 1 cgeng domain users       43 Dez  8  2019 extract.config
-rw-r----- 1 cgeng domain users 33086093 Dez  8  2019 final.raw
-rw-r----- 1 cgeng domain users        6 Dez  8  2019 max_chunk_size
-rw-r----- 1 cgeng domain users     5314 Dez  9  2019 mean.vec
-rw-r----- 1 cgeng domain users        3 Dez  8  2019 min_chunk_size
-rw-r----- 1 cgeng domain users     4979 Dez  8  2019 nnet.config
-rw-r----- 1 cgeng domain users   323246 Dez  9  2019 plda
-rw-r----- 1 cgeng domain users        3 Dez  8  2019 srand
-rw-r----- 1 cgeng domain users   410415 Dez  9  2019 transform.mat
#+end_example


***** anon_xvec_out_dir

wird an zwei stellen definiert:

- baseline/config.sh
- baseline/local/anon/anonymize_data_dir.sh

jeweils als anon_xvec_out_dir=${xvec_nnet_dir}/anon # x-vector extraction output dir

|| exit 1



***** Mein Call

. ./config.sh
nj=$(nproc)
anoni_pool=libritts_train_other_500
xvec_nnet_dir=exp/models/2_xvect_extr/exp/xvector_nnet_1a # x-vector extractor
anon_xvec_out_dir=${xvec_nnet_dir}/anon
# note: man hätte die gpu spezifizieren können!
local/featex/01_extract_xvectors.sh --nj $nj data/${anoni_pool} ${xvec_nnet_dir} ${anon_xvec_out_dir}


Das ist der aufruff für die mfccs:

1267711 cgeng     20   0  177548  16212  12376 S  10,6   0,0   3:30.38 compute-mfcc-feats --write-utt2dur=ark,t:exp/make_mfcc/utt2dur.1 --verbose=2 --config=conf/mfcc.conf scp,p:exp/make_mfcc/wav_libritts_train_other_500.1.scp ark:-


das für die xvectors:

1688328 cgeng     20   0  288316 124212  22512 R  90,8   0,4   1:23.55 nnet3-xvector-compute --use-gpu=no --min-chunk-size=25 --chunk-size=10000 --cache-capacity=64 nnet3-copy --nnet-config=exp/models/2_xvect_extr/exp/xvector_nnet_1a/extract.config exp/models/2_xvect_ex+



***** Log file des Calls


local/featex/01_extract_xvectors.sh --nj $nj data/${anoni_pool} ${xvec_nnet_dir} ${anon_xvec_out_dir}
../env.sh: line 1: [: !=: unary operator expected
steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config conf/mfcc.conf --nj 12 --cmd run.pl data/libritts_train_other_500 exp/make_mfcc /home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/mfcc
../env.sh: line 1: [: !=: unary operator expected
utils/validate_data_dir.sh: Successfully validated data-directory data/libritts_train_other_500
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libritts_train_other_500
fix_data_dir.sh: kept all 205044 utterances.
fix_data_dir.sh: old files are kept in data/libritts_train_other_500/.backup
sid/compute_vad_decision.sh --nj 12 --cmd run.pl data/libritts_train_other_500 exp/make_vad /home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/mfcc
../env.sh: line 1: [: !=: unary operator expected
Created VAD output for libritts_train_other_500
fix_data_dir.sh: kept all 205044 utterances.
fix_data_dir.sh: old files are kept in data/libritts_train_other_500/.backup
sid/nnet3/xvector/extract_xvectors.sh --cmd run.pl --nj 12 exp/models/2_xvect_extr/exp/xvector_nnet_1a data/libritts_train_other_500 exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500
../env.sh: line 1: [: !=: unary operator expected
sid/nnet3/xvector/extract_xvectors.sh: using exp/models/2_xvect_extr/exp/xvector_nnet_1a/extract.config to extract xvectors
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors for data/libritts_train_other_500
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors from nnet
sid/nnet3/xvector/extract_xvectors.sh: combining xvectors across jobs
sid/nnet3/xvector/extract_xvectors.sh: computing mean of xvectors for each speaker

***** Welche Dateien werden erzeugt

ll ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/ -ltr | head

findbydate exp  | head -n 20
2023-02-06 17:12:45.235918822 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.5.log
2023-02-06 17:12:45.143927359 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.10.log
2023-02-06 17:12:45.095931813 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.4.log
2023-02-06 17:12:45.063934783 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.12.log
2023-02-06 17:12:45.015939236 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.2.log
2023-02-06 17:12:44.995941095 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.8.log
2023-02-06 17:12:44.883951518 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.6.log
2023-02-06 17:12:44.651973108 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.9.ark
2023-02-06 17:12:44.651973108 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.9.log
2023-02-06 17:12:44.603977575 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.3.ark
2023-02-06 17:12:44.603977575 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.3.log
2023-02-06 17:12:44.507986509 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.11.ark
2023-02-06 17:12:44.507986509 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.11.log
2023-02-06 17:12:44.479989115 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.7.ark
2023-02-06 17:12:44.479989115 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.7.log
2023-02-06 17:12:44.463990604 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.1.ark
2023-02-06 17:12:44.463990604 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/log/extract.1.log
2023-02-06 17:12:44.403996188 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.5.ark
2023-02-06 17:12:44.260009589 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.4.ark
2023-02-06 17:12:44.248010706 +0100 ./exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500/xvector.8.ark







*** Download and prepare LibriSpeech data sets for training evaluation models (train-other-360)
**** Call Stack

#+include: ./baseline/local/main_get_train_data.sh

**** Assemble Call
train=$data_to_train_eval_models

# from baseline config
corpus: corpora data_url: www.openslr.org/resources/12 part: train-clean-360 LibriSpeech
data_to_train_eval_models=train-clean-360                         # training dataset for evaluation models
data_url_librispeech=www.openslr.org/resources/12
corpora=corpora

**** Log

local/main_get_train_data.sh
../env.sh: line 1: [: !=: unary operator expected
train=train-clean-360
Downloading LibriSpeech data set train-clean-360 for training evaluatio models...
~/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/corpora ~/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline
local/download_and_untar.sh: downloading data from www.openslr.org/resources/12/train-clean-360.tar.gz.  This may take some time, please be patient.
--2023-02-07 10:09:45--  http://www.openslr.org/resources/12/train-clean-360.tar.gz
Resolving www.openslr.org (www.openslr.org)... 46.101.158.64
Connecting to www.openslr.org (www.openslr.org)|46.101.158.64|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 23049477885 (21G) [application/x-gzip]
Saving to: 'train-clean-360.tar.gz'
...
local/download_and_untar.sh: Successfully downloaded and un-tarred corpora/train-clean-360.tar.gz
Preparing data train-clean-360 for training evaluation models...
utils/data/get_utt2dur.sh: segments file does not exist so getting durations from wave files
utils/data/get_utt2dur.sh: could not get utterance lengths from sphere-file headers, using wav-to-duration
utils/data/get_utt2dur.sh: computed data/train-clean-360/utt2dur
utils/validate_data_dir.sh: Successfully validated data-directory data/train-clean-360
local/data_prep_libri.sh: successfully prepared data in data/train-clean-360
Preparing data data for training ASV evaluation model:  spk2utt with real speaker ids...
train-clean-360 --> train-clean-360-asv
utils/copy_data_dir.sh: copied data from data/train-clean-360 to data/train-clean-360-asv
utils/validate_data_dir.sh: Successfully validated data-directory data/train-clean-360-asv
fix_data_dir.sh: kept all 104014 utterances.
fix_data_dir.sh: old files are kept in data/train-clean-360-asv/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/train-clean-360-asv
Done

**** Call to utt2dur

# download und Datenextraction:
local/download_and_untar.sh: Successfully downloaded and un-tarred corpora/train-clean-360.tar.gz
Preparing data train-clean-360 for training evaluation models...
utils/data/get_utt2dur.sh: segments file does not exist so getting durations from wave files
utils/data/get_utt2dur.sh: could not get utterance lengths from sphere-file headers, using wav-to-duration
^[[1;5F

3006729 cgeng     20   0  111320  10644   9928 S   1,3   0,0   0:00.48 wav-to-duration --read-entire-file=false scp:data/train-clean-360/split4utt/4/wav.scp ark,t:data/train-clean-360/split4utt/4/utt2dur





*** # Make evaluation data

#+include: "./baseline/local/main_make_eval_data.sh"

***  # Anonymization of evaluation datasets   local/main_anonymization.sh

#+include: "./baseline/local/main_anonymization.sh"
#+include: "./baseline/local/main_anonymization_cgeng.sh"

#+include: "./baseline/local/anon/anonymize_data_dir.sh"
#+include: "./baseline/local/anon/anonymize_data_dir_cgeng.sh"

Beinhaltet steps:

#+include: "./baseline/local/featex/01_extract_xvectors.sh"
#+include: "./baseline/local/anon/make_pseudospeaker.sh"
#+include: "./baseline/local/featex/02_extract_pitch.sh"
#+include: "./baseline/local/featex/extract_ppg.sh"
#+include: "./baseline/local/anon/make_netcdf.sh"



**** 01_extract_xvectors.sh
Steps:
1. mfcc erzeugen

  #+begin_src  bash
ls /tmp/mfcc -lt
  #+end_src

  #+RESULTS:
  | total      | 6848 |       |        |       |        |     |   |       |                                         |
  | -rw-r--r-- |    1 | cgeng | domain | users | 743933 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.7.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2083 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.7.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 780349 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.1.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2107 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.1.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 693378 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.2.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2107 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.2.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 679981 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.5.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2088 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.5.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 507861 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.8.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2013 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.8.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 571354 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.6.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2063 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.6.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 526244 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.12.ark |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2030 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.12.scp |
  | -rw-r--r-- |    1 | cgeng | domain | users | 468868 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.9.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2017 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.9.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users | 525950 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.10.ark |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2041 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.10.scp |
  | -rw-r--r-- |    1 | cgeng | domain | users | 522093 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.4.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2091 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.4.scp  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2061 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.11.scp |
  | -rw-r--r-- |    1 | cgeng | domain | users | 467954 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.11.ark |
  | -rw-r--r-- |    1 | cgeng | domain | users | 450232 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.3.ark  |
  | -rw-r--r-- |    1 | cgeng | domain | users |   2107 | Feb | 7 | 16:16 | raw_mfcc_libri_dev_enrolls_cgeng.3.scp  |
2. vad erzeugen
#+begin_src  bash
ls /tmp/vad -lt
#+end_src
#+RESULTS:
| total      | 968 |       |        |       |       |     |   |       |                                    |
| -rw-r--r-- |   1 | cgeng | domain | users | 87436 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.10.ark |
| -rw-r--r-- |   1 | cgeng | domain | users |  2116 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.10.scp |
| -rw-r--r-- |   1 | cgeng | domain | users | 92594 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.1.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1711 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.1.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 98079 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.2.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1968 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.2.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 97589 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.5.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  2016 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.5.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 87698 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.7.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1491 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.7.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 73310 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.11.ark |
| -rw-r--r-- |   1 | cgeng | domain | users |  2270 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.11.scp |
| -rw-r--r-- |   1 | cgeng | domain | users | 59807 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.12.ark |
| -rw-r--r-- |   1 | cgeng | domain | users |  1503 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.12.scp |
| -rw-r--r-- |   1 | cgeng | domain | users | 62607 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.3.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1908 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.3.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 70152 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.4.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1955 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.4.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 66092 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.6.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1731 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.6.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 64932 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.8.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1944 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.8.scp  |
| -rw-r--r-- |   1 | cgeng | domain | users | 61156 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.9.ark  |
| -rw-r--r-- |   1 | cgeng | domain | users |  1826 | Feb | 7 | 16:19 | vad_libri_dev_enrolls_cgeng.9.scp  |
3. xvectors erzeugen

#+begin_src  bash
ls /tmp/xvectors -l -R
#+end_src

#+RESULTS:
| /tmp/xvectors:                                      |     |       |        |       |       |     |   |       |                                  |
| total                                               |   4 |       |        |       |       |     |   |       |                                  |
| drwxr-xr-x                                          |   3 | cgeng | domain | users |  4096 | Feb | 7 | 16:21 | xvectors_libri_dev_enrolls_cgeng |
|                                                     |     |       |        |       |       |     |   |       |                                  |
| /tmp/xvectors/xvectors_libri_dev_enrolls_cgeng:     |     |       |        |       |       |     |   |       |                                  |
| total                                               | 872 |       |        |       |       |     |   |       |                                  |
| drwxr-xr-x                                          |   2 | cgeng | domain | users |  4096 | Feb | 7 | 16:21 | log                              |
| -rw-r--r--                                          |   1 | cgeng | domain | users |   246 | Feb | 7 | 16:21 | num_utts.ark                     |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 59822 | Feb | 7 | 16:21 | spk_xvector.ark                  |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2133 | Feb | 7 | 16:21 | spk_xvector.scp                  |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 66376 | Feb | 7 | 16:21 | xvector.10.ark                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2689 | Feb | 7 | 16:21 | xvector.10.scp                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 70550 | Feb | 7 | 16:21 | xvector.11.ark                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2883 | Feb | 7 | 16:21 | xvector.11.scp                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 47695 | Feb | 7 | 16:20 | xvector.12.ark                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  1918 | Feb | 7 | 16:20 | xvector.12.scp                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 53950 | Feb | 7 | 16:21 | xvector.1.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2177 | Feb | 7 | 16:21 | xvector.1.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 62243 | Feb | 7 | 16:21 | xvector.2.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2506 | Feb | 7 | 16:21 | xvector.2.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 60175 | Feb | 7 | 16:21 | xvector.3.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2429 | Feb | 7 | 16:21 | xvector.3.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 62232 | Feb | 7 | 16:21 | xvector.4.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2495 | Feb | 7 | 16:21 | xvector.4.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 64301 | Feb | 7 | 16:21 | xvector.5.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2573 | Feb | 7 | 16:21 | xvector.5.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 55980 | Feb | 7 | 16:21 | xvector.6.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2216 | Feb | 7 | 16:21 | xvector.6.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 47702 | Feb | 7 | 16:20 | xvector.7.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  1902 | Feb | 7 | 16:20 | xvector.7.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 62220 | Feb | 7 | 16:21 | xvector.8.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2483 | Feb | 7 | 16:21 | xvector.8.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 58084 | Feb | 7 | 16:21 | xvector.9.ark                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  2329 | Feb | 7 | 16:21 | xvector.9.scp                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 28600 | Feb | 7 | 16:21 | xvector.scp                      |
|                                                     |     |       |        |       |       |     |   |       |                                  |
| /tmp/xvectors/xvectors_libri_dev_enrolls_cgeng/log: |     |       |        |       |       |     |   |       |                                  |
| total                                               | 148 |       |        |       |       |     |   |       |                                  |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10942 | Feb | 7 | 16:21 | extract.10.log                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 11349 | Feb | 7 | 16:21 | extract.11.log                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  9199 | Feb | 7 | 16:20 | extract.12.log                   |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  9801 | Feb | 7 | 16:21 | extract.1.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10566 | Feb | 7 | 16:21 | extract.2.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10372 | Feb | 7 | 16:21 | extract.3.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10550 | Feb | 7 | 16:21 | extract.4.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10742 | Feb | 7 | 16:21 | extract.5.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  9947 | Feb | 7 | 16:21 | extract.6.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  9196 | Feb | 7 | 16:20 | extract.7.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10535 | Feb | 7 | 16:21 | extract.8.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users | 10168 | Feb | 7 | 16:21 | extract.9.log                    |
| -rw-r--r--                                          |   1 | cgeng | domain | users |  1126 | Feb | 7 | 16:21 | speaker_mean.log                 |








**** make_pseudospeaker.sh

#+include: "./baseline/local/anon/make_pseudospeaker.sh"
    python local/anon/compute_spk_pool_cosine.py ${src_xvec_dir} ${pool_xvec_dir} \
    local/anon/compute_spk_pool_affinity.sh ${plda_dir} ${src_xvec_dir} ${pool_xvec_dir} \

**** yaapt f0 extractor call
3443209 cgeng     20   0 1269284  78204  28168 R 173,9   0,2   0:08.04 python local/featex/f0_yaapt/get_f0.py exp/make_pitch/tmpwav_libri_dev_enrolls.7.wav data/libri_dev_enrolls/yaapt_pitch/5694-64025-0010.f0

**** Log so far


local/main_anonymization.sh
anon_level = spk
libri_dev_enrolls
/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/exp/am_nsf_data


***** For libri_dev_enrolls


 Anonymizing using x-vectors and neural wavform models...
param=libri_dev_enrolls

Stage a.0: Extracting xvectors for libri_dev_enrolls.
created out_dir: exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon
dataname is libri_dev_enrolls{}
steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config conf/mfcc.conf --nj 12 --cmd run.pl data/libri_dev_enrolls exp/make_mfcc /home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/mfcc
steps/make_mfcc.sh: moving data/libri_dev_enrolls/feats.scp to data/libri_dev_enrolls/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libri_dev_enrolls
fix_data_dir.sh: kept all 343 utterances.
fix_data_dir.sh: old files are kept in data/libri_dev_enrolls/.backup
sid/compute_vad_decision.sh --nj 12 --cmd run.pl data/libri_dev_enrolls exp/make_vad /home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/mfcc
sid/compute_vad_decision.sh: moving data/libri_dev_enrolls/vad.scp to data/libri_dev_enrolls/.backup
Created VAD output for libri_dev_enrolls
fix_data_dir.sh: kept all 343 utterances.
fix_data_dir.sh: old files are kept in data/libri_dev_enrolls/.backup
sid/nnet3/xvector/extract_xvectors.sh --cmd run.pl --nj 12 exp/models/2_xvect_extr/exp/xvector_nnet_1a data/libri_dev_enrolls exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls
sid/nnet3/xvector/extract_xvectors.sh: using exp/models/2_xvect_extr/exp/xvector_nnet_1a/extract.config to extract xvectors
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors for data/libri_dev_enrolls
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors from nnet
sid/nnet3/xvector/extract_xvectors.sh: combining xvectors across jobs
sid/nnet3/xvector/extract_xvectors.sh: computing mean of xvectors for each speaker

Stage a.1: Generating pseudo-speakers for libri_dev_enrolls.
src_xvec_dir: exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls
pool_xvec_dir:exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libritts_train_other_500
Computing PLDA affinity scores of each source speaker to each pool speaker.
['local/anon/gen_pseudo_xvecs.py', 'data/libri_dev_enrolls', 'data/libritts_train_other_500', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/spk_pool_scores', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/pseudo_xvecs', 'spk', 'false', 'farthest', '0']
**Same gender speakers will be selected.**
Randomization level: spk
Proximity: farthest
Reading source spk2gender.
Reading source spk2utt.
Reading pool spk2gender.
Reading pool xvectors.
Read  1160 pool xvectors
Writing pseud-speaker xvectors to: exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/pseudo_xvecs
Writing pseudo-speaker spk2gender.
f0_download=true, data_dir=libri_dev_enrolls
Stage a.2: Pitch extraction for libri_dev_enrolls.
local/featex/make_pitch.sh --nj 12 --cmd run.pl data/libri_dev_enrolls exp/make_pitch data/libri_dev_enrolls/pitch
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls
local/featex/make_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
time for yaapt
local/featex/make_pitch.sh: Succeeded creating pitch and POV features for libri_dev_enrolls

Stage a.3: PPG extraction for libri_dev_enrolls.
utils/copy_data_dir.sh: copied data from data/libri_dev_enrolls to data/libri_dev_enrolls_hires
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls_hires
steps/make_mfcc.sh --nj 12 --mfcc-config conf/mfcc_hires.conf --cmd run.pl data/libri_dev_enrolls_hires
steps/make_mfcc.sh: moving data/libri_dev_enrolls_hires/feats.scp to data/libri_dev_enrolls_hires/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls_hires
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libri_dev_enrolls_hires
steps/online/nnet2/extract_ivectors_online.sh --cmd run.pl --nj 12 data/libri_dev_enrolls_hires exp/models/1_asr_am/exp/nnet3_cleaned/extractor exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_enrolls_hires
steps/online/nnet2/extract_ivectors_online.sh: extracting iVectors
steps/online/nnet2/extract_ivectors_online.sh: combining iVectors across jobs
steps/online/nnet2/extract_ivectors_online.sh: done extracting (online) iVectors to exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_enrolls_hires using the extractor in exp/models/1_asr_am/exp/nnet3_cleaned/extractor.
Done

Stage a.4: Make netcdf data for VC.
Writing SCP file..
Writing PPG feats.....
/home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii/pyTools/ioTools/readwrite.py:187: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  datatype = np.dtype((format,1))
Finished writing PPG feats.
Writing xvector and F0 for train.
false
false
/home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii/pyTools/ioTools/readwrite.py:187: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  datatype = np.dtype((format,1))
Stage a.5: Generate melspec from acoustic model for libri_dev_enrolls.
-------------------------------------------------
---  Start program 2023-02-08 10:07:03.492525 ---
-------------------------------------------------
Load module: config
Load module: model
cudnn_deterministic set to False
cudnn_benchmark set to True
---------------------------------------------------------------------
---  Loading dataset libri_dev_enrolls 2023-02-08 10:07:03.787617 ---
---------------------------------------------------------------------
Get data statistis (may be slow due to data I/O)
------------------------------------------------>|
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Merge datasets by: concatenate
Dataset libri_dev_enrolls:
  Time steps: 227416
  Data sequence num: 343
  Maximum sequence length: 3203
  Minimum sequence length: 154
  Inputs
    Dirs:
        /home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/exp/am_nsf_data/libri_dev_enrolls/ppg
        /home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/exp/am_nsf_data/libri_dev_enrolls/xvector
        /home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline/exp/am_nsf_data/libri_dev_enrolls/f0
    Exts:['.ppg', '.xvector', '.f0']
    Dims:[256, 512, 1]
    Reso:[1, 1, 1]
    Norm:[True, True, True]
  Outputs
    Dirs:
    Exts:['.mel']
    Dims:[80]
    Reso:[1]
    Norm:[True]
{'batch_size': 10, 'shuffle': True, 'num_workers': 10, 'sampler': 'block_shuffle_by_length'}

Use single GPU: NVIDIA GeForce GTX 1050 Ti

Model check:
[OK]: prepare_mean_std found
[OK]: normalize_input found
[OK]: normalize_target found
[OK]: denormalize_output found
[OK]: forward found
[OK]: use inference, alternative method for inference
[OK]: loss is ignored, loss defined within model module
[OK]: other_setups is ignored, other setup functions before training
[OK]: flag_validation is ignored, flag to indicate train or validation set
[OK]: validation is ignored, deprecated. Please use model.flag_validation
[OK]: finish_up_inference is ignored, method to finish up work after inference
Model check done

Model infor:
Model(
  (m_base): Sequential(
    (0): Linear(in_features=769, out_features=512, bias=True)
    (1): Tanh()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): Tanh()
    (4): LSTM(512, 128, batch_first=True, bidirectional=True)
  )
  (m_fdback): CombineFeedBack(
    (m_gate): GatedActWithNoise()
    (m_fb_trans): Sequential(
      (0): Linear(in_features=80, out_features=80, bias=True)
      (1): Linear(in_features=80, out_features=80, bias=True)
    )
  )
  (m_fb_proc): Sequential(
    (0): LSTMLayer(
      (m_lstm): LSTM(336, 512, batch_first=True)
    )
    (1): LSTMLayer(
      (m_lstm): LSTM(512, 512, batch_first=True)
    )
  )
  (m_fb_proc_out): Linear(in_features=512, out_features=80, bias=True)
  (m_post): PostNet(
    (m_post): Sequential(
      (0): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (1): GatedActWithNoise()
      (2): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (3): GatedActWithNoise()
      (4): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (5): GatedActWithNoise()
      (6): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (7): GatedActWithNoise()
      (8): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
    )
  )
  (m_loss): MSELoss()
)
Parameter number: 5370752

Start inference (generation):
Generating 1, 106,2428-83699-0031,0,329,0, time cost: 0.060s
Generating 2, 52,1993-147149-0014,0,304,0, time cost: 0.060s
Generating 3, 236,6295-244435-0035,0,318,0, time cost: 0.060s
Generating 4, 266,6345-64257-0014,0,307,0, time cost: 0.060s
Generating 5, 159,3752-4943-0005,0,309,0, time cost: 0.060s
Generating 6, 197,5895-34615-0001,0,329,0, time cost: 0.060s
Generating 7, 124,251-118436-0018,0,281,0, time cost: 0.060s
Generating 8, 248,6313-66125-0020,0,297,0, time cost: 0.060s
Generating 9, 329,84-121123-0014,0,287,0, time cost: 0.060s
Generating 10, 265,6345-64257-0012,0,280,0, time cost: 0.060s
Generating 11, 184,5536-43358-0012,0,337,0, time cost: 0.013s
Generating 12, 226,6295-244435-0003,0,323,0, time cost: 0.013s
Generating 13, 278,652-129742-0011,0,326,0, time cost: 0.013s
Generating 14, 239,6313-66125-0002,0,306,0, time cost: 0.013s
Generating 15, 98,2428-83699-0010,0,310,0, time cost: 0.013s
Generating 16, 84,2277-149874-0021,0,297,0, time cost: 0.013s
Generating 17, 242,6313-66125-0006,0,299,0, time cost: 0.013s
Generating 18, 311,8297-275154-0015,0,320,0, time cost: 0.013s
Generating 19, 105,2428-83699-0026,0,312,0, time cost: 0.013s
Generating 20, 121,251-118436-0010,0,323,0, time cost: 0.013s
Generating 21, 62,2035-147960-0006,0,330,0, time cost: 0.013s
Generating 22, 164,3752-4943-0015,0,294,0, time cost: 0.013s
Generating 23, 15,1462-170138-0015,0,336,0, time cost: 0.013s
Generating 24, 201,5895-34615-0008,0,304,0, time cost: 0.013s
Generating 25, 99,2428-83699-0013,0,327,0, time cost: 0.013s
Generating 26, 107,2428-83699-0032,0,316,0, time cost: 0.013s
Generating 27, 268,6345-64257-0017,0,281,0, time cost: 0.013s
Generating 28, 39,1988-147956-0013,0,287,0, time cost: 0.013s
Generating 29, 309,8297-275154-0013,0,312,0, time cost: 0.013s
Generating 30, 271,6345-64257-0020,0,284,0, time cost: 0.013s
Generating 31, 170,3752-4943-0023,0,304,0, time cost: 0.013s
Generating 32, 51,1993-147149-0010,0,326,0, time cost: 0.013s
Generating 33, 241,6313-66125-0004,0,324,0, time cost: 0.013s
Generating 34, 86,2412-153947-0001,0,321,0, time cost: 0.013s
Generating 35, 287,7976-105575-0002,0,303,0, time cost: 0.013s
Generating 36, 78,2277-149874-0013,0,314,0, time cost: 0.013s
Generating 37, 222,6241-61943-0019,0,289,0, time cost: 0.013s
Generating 38, 330,84-121123-0015,0,302,0, time cost: 0.013s
Generating 39, 211,6241-61943-0001,0,320,0, time cost: 0.013s
Generating 40, 196,5895-34615-0000,0,332,0, time cost: 0.013s
Generating 41, 57,2035-147960-0001,0,391,0, time cost: 0.018s
Generating 42, 232,6295-244435-0024,0,418,0, time cost: 0.018s
Generating 43, 150,3536-23268-0015,0,393,0, time cost: 0.018s
Generating 44, 129,2803-154320-0002,0,351,0, time cost: 0.018s
Generating 45, 172,3752-4943-0026,0,403,0, time cost: 0.018s
Generating 46, 177,5338-24615-0009,0,424,0, time cost: 0.018s
Generating 47, 134,2803-154320-0008,0,357,0, time cost: 0.018s
Generating 48, 246,6313-66125-0014,0,377,0, time cost: 0.018s
Generating 49, 290,7976-105575-0009,0,403,0, time cost: 0.018s
Generating 50, 178,5338-24615-0010,0,387,0, time cost: 0.018s
Generating 51, 283,652-129742-0017,0,339,0, time cost: 0.016s
Generating 52, 257,6319-275224-0012,0,410,0, time cost: 0.016s
Generating 53, 149,3536-23268-0014,0,348,0, time cost: 0.016s
Generating 54, 321,84-121123-0001,0,397,0, time cost: 0.016s
Generating 55, 312,8297-275154-0017,0,368,0, time cost: 0.016s
Generating 56, 281,652-129742-0014,0,393,0, time cost: 0.016s
Generating 57, 66,2035-147960-0012,0,424,0, time cost: 0.016s
Generating 58, 162,3752-4943-0012,0,338,0, time cost: 0.016s
Generating 59, 63,2035-147960-0009,0,348,0, time cost: 0.016s
Generating 60, 35,1988-147956-0005,0,345,0, time cost: 0.016s
Generating 61, 235,6295-244435-0034,0,340,0, time cost: 0.017s
Generating 62, 126,251-118436-0021,0,396,0, time cost: 0.017s
Generating 63, 264,6345-64257-0010,0,397,0, time cost: 0.017s
Generating 64, 136,2803-154320-0011,0,426,0, time cost: 0.017s
Generating 65, 308,8297-275154-0008,0,402,0, time cost: 0.017s
Generating 66, 301,7976-105575-0026,0,353,0, time cost: 0.017s
Generating 67, 115,251-118436-0001,0,371,0, time cost: 0.017s
Generating 68, 135,2803-154320-0010,0,399,0, time cost: 0.017s
Generating 69, 140,2902-9006-0004,0,378,0, time cost: 0.017s
Generating 70, 217,6241-61943-0009,0,383,0, time cost: 0.017s
Generating 71, 214,6241-61943-0004,0,339,0, time cost: 0.017s
Generating 72, 141,2902-9006-0006,0,398,0, time cost: 0.017s
Generating 73, 316,8297-275154-0024,0,365,0, time cost: 0.017s
Generating 74, 277,652-129742-0010,0,338,0, time cost: 0.017s
Generating 75, 218,6241-61943-0011,0,388,0, time cost: 0.017s
Generating 76, 42,1988-147956-0018,0,352,0, time cost: 0.017s
Generating 77, 189,5694-64025-0007,0,390,0, time cost: 0.017s
Generating 78, 331,84-121123-0018,0,353,0, time cost: 0.017s
Generating 79, 60,2035-147960-0004,0,415,0, time cost: 0.017s
Generating 80, 160,3752-4943-0009,0,358,0, time cost: 0.017s
Generating 81, 157,3752-4943-0003,0,623,0, time cost: 0.033s
Generating 82, 48,1993-147149-0000,0,670,0, time cost: 0.033s
Generating 83, 41,1988-147956-0017,0,628,0, time cost: 0.033s
Generating 84, 273,652-129742-0004,0,710,0, time cost: 0.033s
Generating 85, 302,7976-105575-0027,0,666,0, time cost: 0.033s
Generating 86, 27,174-168635-0006,0,655,0, time cost: 0.033s
Generating 87, 43,1988-147956-0020,0,676,0, time cost: 0.033s
Generating 88, 293,7976-105575-0014,0,747,0, time cost: 0.033s
Generating 89, 110,2428-83699-0037,0,638,0, time cost: 0.033s
Generating 90, 341,8842-302196-0009,0,704,0, time cost: 0.033s
Generating 91, 44,1988-147956-0022,0,752,0, time cost: 0.030s
Generating 92, 208,5895-34615-0019,0,684,0, time cost: 0.030s
Generating 93, 207,5895-34615-0017,0,734,0, time cost: 0.030s
Generating 94, 71,2277-149874-0003,0,768,0, time cost: 0.030s
Generating 95, 198,5895-34615-0003,0,659,0, time cost: 0.030s
Generating 96, 225,6241-61943-0024,0,734,0, time cost: 0.030s
Generating 97, 237,6295-244435-0036,0,720,0, time cost: 0.030s
Generating 98, 327,84-121123-0008,0,700,0, time cost: 0.030s
Generating 99, 75,2277-149874-0010,0,740,0, time cost: 0.030s
Generating 100, 270,6345-64257-0019,0,770,0, time cost: 0.030s
Generating 101, 256,6319-275224-0010,0,692,0, time cost: 0.033s
Generating 102, 83,2277-149874-0020,0,736,0, time cost: 0.033s
Generating 103, 336,8842-302196-0002,0,664,0, time cost: 0.033s
Generating 104, 122,251-118436-0014,0,667,0, time cost: 0.033s
Generating 105, 191,5694-64025-0011,0,701,0, time cost: 0.033s
Generating 106, 14,1462-170138-0013,0,700,0, time cost: 0.033s
Generating 107, 114,2428-83699-0042,0,641,0, time cost: 0.033s
Generating 108, 289,7976-105575-0008,0,717,0, time cost: 0.033s
Generating 109, 119,251-118436-0008,0,621,0, time cost: 0.033s
Generating 110, 8,1272-128104-0013,0,708,0, time cost: 0.033s
Generating 111, 305,8297-275154-0004,0,664,0, time cost: 0.030s
Generating 112, 116,251-118436-0002,0,695,0, time cost: 0.030s
Generating 113, 210,6241-61943-0000,0,693,0, time cost: 0.030s
Generating 114, 61,2035-147960-0005,0,657,0, time cost: 0.030s
Generating 115, 322,84-121123-0003,0,678,0, time cost: 0.030s
Generating 116, 87,2412-153947-0002,0,658,0, time cost: 0.030s
Generating 117, 45,1988-147956-0026,0,690,0, time cost: 0.030s
Generating 118, 334,84-121123-0025,0,624,0, time cost: 0.030s
Generating 119, 152,3536-23268-0018,0,757,0, time cost: 0.030s
Generating 120, 72,2277-149874-0005,0,635,0, time cost: 0.030s
Generating 121, 206,5895-34615-0014,0,514,0, time cost: 0.022s
Generating 122, 161,3752-4943-0010,0,506,0, time cost: 0.022s
Generating 123, 0,1272-128104-0000,0,584,0, time cost: 0.022s
Generating 124, 77,2277-149874-0012,0,506,0, time cost: 0.022s
Generating 125, 325,84-121123-0006,0,560,0, time cost: 0.022s
Generating 126, 6,1272-128104-0010,0,558,0, time cost: 0.022s
Generating 127, 4,1272-128104-0006,0,562,0, time cost: 0.022s
Generating 128, 299,7976-105575-0022,0,536,0, time cost: 0.022s
Generating 129, 280,652-129742-0013,0,558,0, time cost: 0.022s
Generating 130, 247,6313-66125-0017,0,505,0, time cost: 0.022s
Generating 131, 169,3752-4943-0022,0,518,0, time cost: 0.024s
Generating 132, 231,6295-244435-0018,0,531,0, time cost: 0.024s
Generating 133, 163,3752-4943-0013,0,552,0, time cost: 0.024s
Generating 134, 288,7976-105575-0005,0,554,0, time cost: 0.024s
Generating 135, 342,8842-302196-0012,0,561,0, time cost: 0.024s
Generating 136, 219,6241-61943-0012,0,584,0, time cost: 0.024s
Generating 137, 37,1988-147956-0009,0,514,0, time cost: 0.024s
Generating 138, 16,1462-170138-0017,0,619,0, time cost: 0.024s
Generating 139, 337,8842-302196-0004,0,572,0, time cost: 0.024s
Generating 140, 339,8842-302196-0007,0,620,0, time cost: 0.024s
Generating 141, 59,2035-147960-0003,0,582,0, time cost: 0.024s
Generating 142, 263,6345-64257-0004,0,603,0, time cost: 0.024s
Generating 143, 36,1988-147956-0007,0,585,0, time cost: 0.024s
Generating 144, 252,6313-66125-0025,0,530,0, time cost: 0.024s
Generating 145, 340,8842-302196-0008,0,529,0, time cost: 0.024s
Generating 146, 118,251-118436-0005,0,529,0, time cost: 0.024s
Generating 147, 97,2428-83699-0007,0,569,0, time cost: 0.024s
Generating 148, 74,2277-149874-0008,0,537,0, time cost: 0.024s
Generating 149, 186,5536-43358-0015,0,594,0, time cost: 0.024s
Generating 150, 260,6319-275224-0019,0,576,0, time cost: 0.024s
Generating 151, 221,6241-61943-0017,0,607,0, time cost: 0.024s
Generating 152, 139,2803-154320-0014,0,527,0, time cost: 0.024s
Generating 153, 192,5694-64025-0015,0,505,0, time cost: 0.024s
Generating 154, 47,1988-147956-0028,0,586,0, time cost: 0.024s
Generating 155, 96,2412-153947-0016,0,517,0, time cost: 0.024s
Generating 156, 171,3752-4943-0024,0,564,0, time cost: 0.024s
Generating 157, 17,1462-170138-0022,0,617,0, time cost: 0.024s
Generating 158, 284,652-129742-0018,0,546,0, time cost: 0.024s
Generating 159, 267,6345-64257-0016,0,576,0, time cost: 0.024s
Generating 160, 292,7976-105575-0012,0,514,0, time cost: 0.024s
Generating 161, 183,5536-43358-0010,0,812,0, time cost: 0.038s
Generating 162, 203,5895-34615-0010,0,775,0, time cost: 0.038s
Generating 163, 209,5895-34615-0020,0,951,0, time cost: 0.038s
Generating 164, 31,174-168635-0019,0,798,0, time cost: 0.038s
Generating 165, 88,2412-153947-0004,0,870,0, time cost: 0.038s
Generating 166, 250,6313-66125-0023,0,933,0, time cost: 0.038s
Generating 167, 91,2412-153947-0009,0,870,0, time cost: 0.038s
Generating 168, 64,2035-147960-0010,0,957,0, time cost: 0.038s
Generating 169, 28,174-168635-0012,0,834,0, time cost: 0.038s
Generating 170, 155,3752-4943-0000,0,881,0, time cost: 0.038s
Generating 171, 104,2428-83699-0025,0,799,0, time cost: 0.037s
Generating 172, 153,3536-23268-0026,0,881,0, time cost: 0.037s
Generating 173, 272,652-129742-0001,0,864,0, time cost: 0.037s
Generating 174, 319,8297-275154-0027,0,873,0, time cost: 0.037s
Generating 175, 5,1272-128104-0007,0,922,0, time cost: 0.037s
Generating 176, 18,1462-170138-0023,0,948,0, time cost: 0.037s
Generating 177, 34,1988-147956-0004,0,901,0, time cost: 0.037s
Generating 178, 181,5536-43358-0007,0,940,0, time cost: 0.037s
Generating 179, 195,5694-64025-0019,0,885,0, time cost: 0.037s
Generating 180, 112,2428-83699-0040,0,781,0, time cost: 0.037s
Generating 181, 58,2035-147960-0002,0,882,0, time cost: 0.036s
Generating 182, 279,652-129742-0012,0,927,0, time cost: 0.036s
Generating 183, 147,3536-23268-0007,0,919,0, time cost: 0.036s
Generating 184, 108,2428-83699-0034,0,810,0, time cost: 0.036s
Generating 185, 262,6345-64257-0003,0,876,0, time cost: 0.036s
Generating 186, 120,251-118436-0009,0,894,0, time cost: 0.036s
Generating 187, 82,2277-149874-0019,0,843,0, time cost: 0.036s
Generating 188, 230,6295-244435-0017,0,853,0, time cost: 0.036s
Generating 189, 79,2277-149874-0014,0,858,0, time cost: 0.036s
Generating 190, 228,6295-244435-0009,0,825,0, time cost: 0.036s
Generating 191, 274,652-129742-0006,0,910,0, time cost: 0.037s
Generating 192, 46,1988-147956-0027,0,771,0, time cost: 0.037s
Generating 193, 21,1673-143396-0002,0,783,0, time cost: 0.037s
Generating 194, 90,2412-153947-0007,0,872,0, time cost: 0.037s
Generating 195, 3,1272-128104-0005,0,899,0, time cost: 0.037s
Generating 196, 123,251-118436-0016,0,895,0, time cost: 0.037s
Generating 197, 213,6241-61943-0003,0,781,0, time cost: 0.037s
Generating 198, 49,1993-147149-0001,0,952,0, time cost: 0.037s
Generating 199, 13,1462-170138-0010,0,860,0, time cost: 0.037s
Generating 200, 56,2035-147960-0000,0,900,0, time cost: 0.037s
Generating 201, 269,6345-64257-0018,0,477,0, time cost: 0.019s
Generating 202, 215,6241-61943-0005,0,488,0, time cost: 0.019s
Generating 203, 314,8297-275154-0020,0,445,0, time cost: 0.019s
Generating 204, 243,6313-66125-0007,0,491,0, time cost: 0.019s
Generating 205, 81,2277-149874-0018,0,500,0, time cost: 0.019s
Generating 206, 333,84-121123-0023,0,467,0, time cost: 0.019s
Generating 207, 179,5338-24615-0012,0,428,0, time cost: 0.019s
Generating 208, 148,3536-23268-0009,0,430,0, time cost: 0.019s
Generating 209, 20,1462-170138-0027,0,499,0, time cost: 0.019s
Generating 210, 32,174-168635-0022,0,432,0, time cost: 0.019s
Generating 211, 234,6295-244435-0031,0,473,0, time cost: 0.019s
Generating 212, 318,8297-275154-0026,0,487,0, time cost: 0.019s
Generating 213, 307,8297-275154-0007,0,447,0, time cost: 0.019s
Generating 214, 80,2277-149874-0015,0,471,0, time cost: 0.019s
Generating 215, 275,652-129742-0007,0,487,0, time cost: 0.019s
Generating 216, 317,8297-275154-0025,0,486,0, time cost: 0.019s
Generating 217, 102,2428-83699-0020,0,487,0, time cost: 0.019s
Generating 218, 240,6313-66125-0003,0,456,0, time cost: 0.019s
Generating 219, 109,2428-83699-0036,0,458,0, time cost: 0.019s
Generating 220, 38,1988-147956-0012,0,455,0, time cost: 0.019s
Generating 221, 205,5895-34615-0013,0,473,0, time cost: 0.019s
Generating 222, 251,6313-66125-0024,0,439,0, time cost: 0.019s
Generating 223, 224,6241-61943-0023,0,434,0, time cost: 0.019s
Generating 224, 65,2035-147960-0011,0,436,0, time cost: 0.019s
Generating 225, 323,84-121123-0004,0,438,0, time cost: 0.019s
Generating 226, 101,2428-83699-0019,0,489,0, time cost: 0.019s
Generating 227, 258,6319-275224-0013,0,485,0, time cost: 0.019s
Generating 228, 131,2803-154320-0005,0,475,0, time cost: 0.019s
Generating 229, 138,2803-154320-0013,0,435,0, time cost: 0.019s
Generating 230, 168,3752-4943-0020,0,486,0, time cost: 0.019s
Generating 231, 70,2035-147960-0016,0,488,0, time cost: 0.019s
Generating 232, 133,2803-154320-0007,0,449,0, time cost: 0.019s
Generating 233, 29,174-168635-0014,0,481,0, time cost: 0.019s
Generating 234, 298,7976-105575-0021,0,464,0, time cost: 0.019s
Generating 235, 291,7976-105575-0010,0,451,0, time cost: 0.019s
Generating 236, 300,7976-105575-0023,0,476,0, time cost: 0.019s
Generating 237, 296,7976-105575-0018,0,427,0, time cost: 0.019s
Generating 238, 249,6313-66125-0021,0,496,0, time cost: 0.019s
Generating 239, 68,2035-147960-0014,0,445,0, time cost: 0.019s
Generating 240, 188,5694-64025-0003,0,490,0, time cost: 0.019s
Generating 241, 146,3536-23268-0002,0,1048,0, time cost: 0.057s
Generating 242, 95,2412-153947-0015,0,1101,0, time cost: 0.057s
Generating 243, 303,8297-275154-0000,0,1020,0, time cost: 0.057s
Generating 244, 261,6319-275224-0020,0,1192,0, time cost: 0.057s
Generating 245, 145,2902-9006-0019,0,1421,0, time cost: 0.057s
Generating 246, 173,5338-24615-0000,0,1001,0, time cost: 0.057s
Generating 247, 158,3752-4943-0004,0,1399,0, time cost: 0.057s
Generating 248, 127,2803-154320-0000,0,1146,0, time cost: 0.057s
Generating 249, 180,5536-43358-0006,0,1039,0, time cost: 0.057s
Generating 250, 1,1272-128104-0002,0,1247,0, time cost: 0.057s
Generating 251, 185,5536-43358-0013,0,1038,0, time cost: 0.055s
Generating 252, 304,8297-275154-0002,0,974,0, time cost: 0.055s
Generating 253, 187,5694-64025-0002,0,1094,0, time cost: 0.055s
Generating 254, 137,2803-154320-0012,0,979,0, time cost: 0.055s
Generating 255, 156,3752-4943-0001,0,1106,0, time cost: 0.055s
Generating 256, 154,3536-23268-0027,0,1030,0, time cost: 0.055s
Generating 257, 294,7976-105575-0016,0,1019,0, time cost: 0.055s
Generating 258, 89,2412-153947-0006,0,1166,0, time cost: 0.055s
Generating 259, 143,2902-9006-0009,0,1195,0, time cost: 0.055s
Generating 260, 33,1988-147956-0001,0,1419,0, time cost: 0.055s
Generating 261, 276,652-129742-0009,0,1395,0, time cost: 0.058s
Generating 262, 130,2803-154320-0004,0,1199,0, time cost: 0.058s
Generating 263, 26,174-168635-0004,0,1275,0, time cost: 0.058s
Generating 264, 2,1272-128104-0003,0,988,0, time cost: 0.058s
Generating 265, 94,2412-153947-0014,0,1278,0, time cost: 0.058s
Generating 266, 282,652-129742-0015,0,1179,0, time cost: 0.058s
Generating 267, 254,6319-275224-0001,0,1216,0, time cost: 0.058s
Generating 268, 117,251-118436-0003,0,1100,0, time cost: 0.058s
Generating 269, 54,1993-147149-0028,0,1015,0, time cost: 0.058s
Generating 270, 142,2902-9006-0008,0,1106,0, time cost: 0.058s
Generating 271, 259,6319-275224-0014,0,1071,0, time cost: 0.051s
Generating 272, 176,5338-24615-0007,0,1006,0, time cost: 0.051s
Generating 273, 125,251-118436-0019,0,1146,0, time cost: 0.051s
Generating 274, 12,1462-170138-0005,0,1315,0, time cost: 0.051s
Generating 275, 229,6295-244435-0016,0,1149,0, time cost: 0.051s
Generating 276, 193,5694-64025-0016,0,1070,0, time cost: 0.051s
Generating 277, 151,3536-23268-0016,0,1130,0, time cost: 0.051s
Generating 278, 92,2412-153947-0011,0,1011,0, time cost: 0.051s
Generating 279, 204,5895-34615-0012,0,1032,0, time cost: 0.051s
Generating 280, 227,6295-244435-0004,0,1230,0, time cost: 0.051s
Generating 281, 132,2803-154320-0006,0,216,0, time cost: 0.011s
Generating 282, 285,652-129742-0019,0,277,0, time cost: 0.011s
Generating 283, 320,84-121123-0000,0,207,0, time cost: 0.011s
Generating 284, 233,6295-244435-0027,0,240,0, time cost: 0.011s
Generating 285, 100,2428-83699-0014,0,220,0, time cost: 0.011s
Generating 286, 306,8297-275154-0005,0,276,0, time cost: 0.011s
Generating 287, 73,2277-149874-0006,0,273,0, time cost: 0.011s
Generating 288, 295,7976-105575-0017,0,192,0, time cost: 0.011s
Generating 289, 244,6313-66125-0009,0,269,0, time cost: 0.011s
Generating 290, 111,2428-83699-0039,0,196,0, time cost: 0.011s
Generating 291, 238,6313-66125-0000,0,234,0, time cost: 0.011s
Generating 292, 245,6313-66125-0012,0,227,0, time cost: 0.011s
Generating 293, 315,8297-275154-0023,0,258,0, time cost: 0.011s
Generating 294, 166,3752-4943-0017,0,226,0, time cost: 0.011s
Generating 295, 85,2412-153947-0000,0,253,0, time cost: 0.011s
Generating 296, 332,84-121123-0022,0,259,0, time cost: 0.011s
Generating 297, 202,5895-34615-0009,0,276,0, time cost: 0.011s
Generating 298, 19,1462-170138-0026,0,237,0, time cost: 0.011s
Generating 299, 69,2035-147960-0015,0,154,0, time cost: 0.011s
Generating 300, 9,1272-128104-0014,0,223,0, time cost: 0.011s
Generating 301, 93,2412-153947-0012,0,196,0, time cost: 0.011s
Generating 302, 103,2428-83699-0021,0,280,0, time cost: 0.011s
Generating 303, 200,5895-34615-0006,0,251,0, time cost: 0.011s
Generating 304, 212,6241-61943-0002,0,272,0, time cost: 0.011s
Generating 305, 223,6241-61943-0021,0,250,0, time cost: 0.011s
Generating 306, 165,3752-4943-0016,0,247,0, time cost: 0.011s
Generating 307, 326,84-121123-0007,0,198,0, time cost: 0.011s
Generating 308, 297,7976-105575-0020,0,207,0, time cost: 0.011s
Generating 309, 113,2428-83699-0041,0,205,0, time cost: 0.011s
Generating 310, 216,6241-61943-0007,0,262,0, time cost: 0.011s
Generating 311, 11,1462-170138-0003,0,230,0, time cost: 0.011s
Generating 312, 40,1988-147956-0014,0,217,0, time cost: 0.011s
Generating 313, 286,7976-105575-0001,0,278,0, time cost: 0.011s
Generating 314, 328,84-121123-0013,0,238,0, time cost: 0.011s
Generating 315, 194,5694-64025-0018,0,267,0, time cost: 0.011s
Generating 316, 220,6241-61943-0015,0,247,0, time cost: 0.011s
Generating 317, 76,2277-149874-0011,0,245,0, time cost: 0.011s
Generating 318, 167,3752-4943-0019,0,248,0, time cost: 0.011s
Generating 319, 313,8297-275154-0018,0,219,0, time cost: 0.011s
Generating 320, 67,2035-147960-0013,0,266,0, time cost: 0.011s
Generating 321, 10,1462-170138-0000,0,1453,0, time cost: 0.125s
Generating 322, 324,84-121123-0005,0,1594,0, time cost: 0.125s
Generating 323, 335,8842-302196-0000,0,1463,0, time cost: 0.125s
Generating 324, 144,2902-9006-0018,0,3203,0, time cost: 0.125s
Generating 325, 253,6313-66125-0027,0,1445,0, time cost: 0.125s
Generating 326, 182,5536-43358-0008,0,2037,0, time cost: 0.125s
Generating 327, 128,2803-154320-0001,0,1554,0, time cost: 0.125s
Generating 328, 175,5338-24615-0005,0,1775,0, time cost: 0.125s
Generating 329, 24,1673-143396-0012,0,1445,0, time cost: 0.125s
Generating 330, 199,5895-34615-0004,0,1593,0, time cost: 0.125s
Generating 331, 55,1993-147149-0030,0,1550,0, time cost: 0.094s
Generating 332, 255,6319-275224-0008,0,1843,0, time cost: 0.094s
Generating 333, 25,1673-143396-0016,0,1444,0, time cost: 0.094s
Generating 334, 50,1993-147149-0003,0,1428,0, time cost: 0.094s
Generating 335, 53,1993-147149-0022,0,1652,0, time cost: 0.094s
Generating 336, 23,1673-143396-0009,0,1644,0, time cost: 0.094s
Generating 337, 338,8842-302196-0005,0,2343,0, time cost: 0.094s
Generating 338, 310,8297-275154-0014,0,1807,0, time cost: 0.094s
Generating 339, 190,5694-64025-0010,0,2160,0, time cost: 0.094s
Generating 340, 7,1272-128104-0011,0,1510,0, time cost: 0.094s
local/vc/am_pytorch/01_gen.sh: line 50: 3453824 Segmentation fault      (core dumped) python ${proj_dir}/main.py --inference --module-config ${config_file} --cudnn-deterministic-toggle --batch-size ${batch_size} --num-workers ${batch_size} --sampler block_shuffle_by_length --cudnn-benchmark-toggle --ignore-cached-file-infor --output-dir ${output_dir} --trained-model ${TEMP_ACOUSTIC_NETWORK_PATH}
(vpc) cgeng@ap-cgeng:~/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/baseline$

3928631 cgeng     20   0 1225404  67128  28200 R  26,1   0,2   0:01.30 python local/featex/f0_yaapt/get_f0.py exp/make_pitch/tmpwav_libri_dev_trials_f.5.wav data/libri_dev_trials_f/yaapt_pitch/3081-166546-0002+
3944003 cgeng     20   0  278168 108560  22592 R  99,3   0,3   1:47.64 nnet3-compute --extra-left-context=0 --extra-right-context=0 --extra-left-context-initial=-1 --extra-right-context-final=-1 --frames-per-c+



3944003 cgeng     20   0  278168 108560  22592 R  99,3   0,3   2:19.35 nnet3-compute --extra-left-context=0 --extra-right-context=0 --extra-left-context-initial=-1 --extra-right-context-final=-1 --frames-per-chunk=50 --use-gpu=yes --online-ivector-period=10 --online-ivectors=scp:exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_trials_f_hires/ivector_online.scp exp/models/1_asr_am/exp/chain_cleaned/tdnn_1d_sp/prefinal-l.raw ark:apply-cmvn --norm-means=false --norm-vars=false --utt2spk=ark:data/libr+


***** For libri_dev_trials_f


Fails for Sample 1000 due to cuda memory

Generating 1000, 871,6345-93306-0019,0,122400,0, time cost: 0.793s
Traceback (most recent call last):
  File "/home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/projects/nsf/main.py", line 211, in <module>
    main()
  File "/home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/projects/nsf/main.py", line 205, in main
    nii_nn_wrapper.f_inference_wrapper(args, model, device, \
  File "/home/audeering.local/cgeng/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/core_scripts/nn_manager/nn_manager.py", line 603, in f_inference_wrapper
    data_gen = infer_func(data_in)
  File "/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/projects/nsf/model.py", line 903, in forward
    output = self.m_filter(har_source, noi_source, cond_feat, cut_f)
  File "/home/audeering.local/cgeng/.envs/vpc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/projects/nsf/model.py", line 762, in forward
    har_component = l_har_block(har_component, cond_feat)
  File "/home/audeering.local/cgeng/.envs/vpc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/projects/nsf/model.py", line 405, in forward
    tmp_hidden = tmp_hidden + l_conv(tmp_hidden) + context
  File "/home/audeering.local/cgeng/.envs/vpc/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/audeering.local/cgeng/Data/Data_HDD/work/code/Voice-Privacy-Challenge-2022ap-cgeng.fritz.box/nii_pytorch/projects/nsf/model.py", line 92, in forward
    x = torch_nn_func.pad(data.permute(0, 2, 1).unsqueeze(2), \
  File "/home/audeering.local/cgeng/.envs/vpc/lib/python3.8/site-packages/torch/nn/functional.py", line 4000, in _pad
    return _VF.constant_pad_nd(input, pad, value)
RuntimeError: CUDA out of memory. Tried to allocate 620.00 MiB (GPU 0; 3.95 GiB total capacity; 1.94 GiB already allocated; 346.88 MiB free; 2.80 GiB reserved in total by PyTorch)
corrupted size vs. prev_size
local/vc/nsf_pytorch/01_gen.sh: line 50: 3947377 Aborted                 (core dumped) python ${proj_dir}/main.py --inference --module-config ${config_file} --ignore-cached-file-infor --batch-size ${batch_size} --num-workers ${batch_size} --sampler block_shuffle_by_length --cudnn-deterministic-toggle --cudnn-benchmark-toggle --output-dir ${output_dir} --trunc-input-length-for-inference ${inf_trunc_option} --trained-model ${TEMP_NSF_NETWORK_PATH}



* Compute3

** My Seg Fault in baseline/run.sh local/main_anonymization.sh

in baseline:
 source env.sh
 local/main_anonymization.sh

Mein Aufruf
#local/main_anonymization.sh

# das hier ist der Zwischenschritt:
/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/local/anon/anonymize_data_dir.sh

Der Fehler selbst tritt auf in:
local/vc/am_pytorch/01_gen.sh


Der Aufruf der direkt zum Fehler Führt ist:
File: baseline/local/vc/am_pytorch/01_angen.sh
50:1:python ${proj_dir}/main.py --inference --module-config ${config_file} \



*** Call Hierarchy

local/main_anonymization.sh -> local/anon/anonymize_data_dir.sh ->  local/vc/am_pytorch/01_gen.sh

*** Aufruf von =local/anon/anonymize_data_dir.sh= in main_anonymization

    printf "${GREEN}\n Anonymizing using x-vectors and neural wavform models...${NC}\n"
    ppg_dir=${ppg_model}/nnet3_cleaned
    local/anon/anonymize_data_dir.sh \
      --nj $nj --anoni-pool $anoni_pool \
      --data-netcdf $data_netcdf \
      --ppg-model $ppg_model --ppg-dir $ppg_dir \
      --xvec-nnet-dir $xvec_nnet_dir \
      --anon-xvec-out-dir $anon_xvec_out_dir --plda-dir $xvec_nnet_dir \
      --pseudo-xvec-rand-level $anon_level --distance $distance \
      --proximity $proximity --cross-gender $cross_gender \
      --rand-seed $rand_seed \
      --anon-data-suffix $anon_data_suffix \
      --model-type $tts_type \
      --inference-trunc-len $inference_trunc_len \
      --inference-batch-size-am $inference_batch_size_am \
      --inference-batch-size-wav $inference_batch_size_wav \
      $dset



*** logs


#+begin_example
Generating 338, 310,8297-275154-0014,0,1807,0, time cost: 0.095s
Generating 339, 190,5694-64025-0010,0,2160,0, time cost: 0.095s
Generating 340, 7,1272-128104-0011,0,1510,0, time cost: 0.095s
local/vc/am_pytorch/01_gen.sh: line 50: 56543 Segmentation fault      (core dumped) python ${proj_dir}/main.py --inference --module-config ${config_file} --cudnn-deterministic-toggle --batch-size ${batch_size} --num-workers ${batch_size} --sampler block_shuffle_by_length --cudnn-benchmark-toggle --ignore-cached-file-infor --output-dir ${output_dir} --trained-model ${TEMP_ACOUSTIC_NETWORK_PATH}
(base) cgeng@compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline$ utils/combine_data.sh
utils/combine_data.sh
Usage: combine_data.sh [--extra-files 'file1 file2'] <dest-data-dir> <src-data-dir1> <src-data-dir2> ...
Note, files that don't appear in all source dirs will not be combined,
with the exception of utt2uniq and segments, which are created where necessary.
(base) cgeng@compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline$ #local/main_anonymization.sh
(base) cgeng@compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline$
#+end_example

*** More logs from /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/local/anon/anonymize_data_dir.sh

**** Stage a.0: Extracting xvectors for libri_dev_enrolls.
steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config conf/mfcc.conf --nj 16 --cmd run.pl data/libri_dev_enrolls exp/make_mfcc /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/mfcc
steps/make_mfcc.sh: moving data/libri_dev_enrolls/feats.scp to data/libri_dev_enrolls/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libri_dev_enrolls
fix_data_dir.sh: kept all 343 utterances.
fix_data_dir.sh: old files are kept in data/libri_dev_enrolls/.backup
sid/compute_vad_decision.sh --nj 16 --cmd run.pl data/libri_dev_enrolls exp/make_vad /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/mfcc
sid/compute_vad_decision.sh: moving data/libri_dev_enrolls/vad.scp to data/libri_dev_enrolls/.backup
Created VAD output for libri_dev_enrolls
fix_data_dir.sh: kept all 343 utterances.
fix_data_dir.sh: old files are kept in data/libri_dev_enrolls/.backup
sid/nnet3/xvector/extract_xvectors.sh --cmd run.pl --nj 16 exp/models/2_xvect_extr/exp/xvector_nnet_1a data/libri_dev_enrolls exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls
sid/nnet3/xvector/extract_xvectors.sh: using exp/models/2_xvect_extr/exp/xvector_nnet_1a/extract.config to extract xvectors
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors for data/libri_dev_enrolls
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors from nnet
sid/nnet3/xvector/extract_xvectors.sh: combining xvectors across jobs
sid/nnet3/xvector/extract_xvectors.sh: computing mean of xvectors for each speaker

**** Stage a.1: Generating pseudo-speakers for libri_dev_enrolls.
Computing PLDA affinity scores of each source speaker to each pool speaker.
['local/anon/gen_pseudo_xvecs.py', 'data/libri_dev_enrolls', 'data/libritts_train_other_500', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/spk_pool_scores', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/pseudo_xvecs', 'spk', 'false', 'farthest', '0']
**Same gender speakers will be selected.**
Randomization level: spk
Proximity: farthest
Reading source spk2gender.
Reading source spk2utt.
Reading pool spk2gender.
Reading pool xvectors.
Read  1160 pool xvectors
Writing pseud-speaker xvectors to: exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/pseudo_xvecs
Writing pseudo-speaker spk2gender.
f0_download=true, data_dir=libri_dev_enrolls

**** Stage a.2: Pitch extraction for libri_dev_enrolls.
local/featex/make_pitch.sh --nj 16 --cmd run.pl data/libri_dev_enrolls exp/make_pitch data/libri_dev_enrolls/pitch
local/featex/make_pitch.sh: moving data/libri_dev_enrolls/pitch.scp to data/libri_dev_enrolls/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls
local/featex/make_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
time for yaapt

**** Stage a.3: PPG extraction for libri_dev_enrolls.
utils/copy_data_dir.sh: copied data from data/libri_dev_enrolls to data/libri_dev_enrolls_hires
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls_hires
steps/make_mfcc.sh --nj 16 --mfcc-config conf/mfcc_hires.conf --cmd run.pl data/libri_dev_enrolls_hires
steps/make_mfcc.sh: moving data/libri_dev_enrolls_hires/feats.scp to data/libri_dev_enrolls_hires/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls_hires
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libri_dev_enrolls_hires
steps/online/nnet2/extract_ivectors_online.sh --cmd run.pl --nj 16 data/libri_dev_enrolls_hires exp/models/1_asr_am/exp/nnet3_cleaned/extractor exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_enrolls_hires
steps/online/nnet2/extract_ivectors_online.sh: extracting iVectors
steps/online/nnet2/extract_ivectors_online.sh: combining iVectors across jobs
steps/online/nnet2/extract_ivectors_online.sh: done extracting (online) iVectors to exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_enrolls_hires using the extractor in exp/models/1_asr_am/exp/nnet3_cleaned/extractor.
Done


**** Stage a.4: Make netcdf data for VC.
Writing SCP file..
Der ppg-file_ exp/models/1_asr_am/exp/nnet3_cleaned/ppg_libri_dev_enrolls/phone_post.scp
Writing PPG features /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/ppg
/data/work3/cgeng/Voice-Privacy-Challenge-2022/nii/pyTools/ioTools/readwrite.py:187: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  datatype = np.dtype((format,1))
Finished writing PPG feats.
Writing xvector and F0 for train.
false
false
/data/work3/cgeng/Voice-Privacy-Challenge-2022/nii/pyTools/ioTools/readwrite.py:187: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  datatype = np.dtype((format,1))

**** Stage a.5: Generate melspec from acoustic model for libri_dev_enrolls.
Etwas debug info für mich
proj_dir: /data/work3/cgeng/Voice-Privacy-Challenge-2022/nii_pytorch/projects/am
config_file: config
batch_size: 10
output_dir: /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/am_pt_out_mel
TEMP_ACOUSTIC_NETWORK_PATH: /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/models/3_ss_am_pt/trained_network.pt
-------------------------------------------------
---  Start program 2023-01-31 09:48:50.966738 ---
-------------------------------------------------
Load module: config
Load module: model
cudnn_deterministic set to False
cudnn_benchmark set to True
---------------------------------------------------------------------
---  Loading dataset libri_dev_enrolls 2023-01-31 09:48:51.424183 ---
---------------------------------------------------------------------
Get data statistis (may be slow due to data I/O)
------------------------------------------------>|
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Merge datasets by: concatenate
Dataset libri_dev_enrolls:
  Time steps: 227416
  Data sequence num: 343
  Maximum sequence length: 3203
  Minimum sequence length: 154
  Inputs
    Dirs:
        /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/ppg
        /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/xvector
        /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/f0
    Exts:['.ppg', '.xvector', '.f0']
    Dims:[256, 512, 1]
    Reso:[1, 1, 1]
    Norm:[True, True, True]
  Outputs
    Dirs:
    Exts:['.mel']
    Dims:[80]
    Reso:[1]
    Norm:[True]
{'batch_size': 10, 'shuffle': True, 'num_workers': 10, 'sampler': 'block_shuffle_by_length'}

Use single GPU: GeForce GTX 1080 Ti

Model check:
[OK]: prepare_mean_std found
[OK]: normalize_input found
[OK]: normalize_target found
[OK]: denormalize_output found
[OK]: forward found
[OK]: use inference, alternative method for inference
[OK]: loss is ignored, loss defined within model module
[OK]: other_setups is ignored, other setup functions before training
[OK]: flag_validation is ignored, flag to indicate train or validation set
[OK]: validation is ignored, deprecated. Please use model.flag_validation
[OK]: finish_up_inference is ignored, method to finish up work after inference
Model check done

Model infor:
Model(
  (m_base): Sequential(
    (0): Linear(in_features=769, out_features=512, bias=True)
    (1): Tanh()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): Tanh()
    (4): LSTM(512, 128, batch_first=True, bidirectional=True)
  )
  (m_fdback): CombineFeedBack(
    (m_gate): GatedActWithNoise()
    (m_fb_trans): Sequential(
      (0): Linear(in_features=80, out_features=80, bias=True)
      (1): Linear(in_features=80, out_features=80, bias=True)
    )
  )
  (m_fb_proc): Sequential(
    (0): LSTMLayer(
      (m_lstm): LSTM(336, 512, batch_first=True)
    )
    (1): LSTMLayer(
      (m_lstm): LSTM(512, 512, batch_first=True)
    )
  )
  (m_fb_proc_out): Linear(in_features=512, out_features=80, bias=True)
  (m_post): PostNet(
    (m_post): Sequential(
      (0): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (1): GatedActWithNoise()
      (2): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (3): GatedActWithNoise()
      (4): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (5): GatedActWithNoise()
      (6): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (7): GatedActWithNoise()
      (8): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
    )
  )
  (m_loss): MSELoss()
)
Parameter number: 5370752



Start inference (generation):
Generating 1, 106,2428-83699-0031,0,329,0, time cost: 0.063s
Generating 2, 52,1993-147149-0014,0,304,0, time cost: 0.063s
Generating 3, 236,6295-244435-0035,0,318,0, time cost: 0.063s
Generating 4, 266,6345-64257-0014,0,307,0, time cost: 0.063s
Generating 5, 159,3752-4943-0005,0,309,0, time cost: 0.063s
Generating 6, 197,5895-34615-0001,0,329,0, time cost: 0.063s
Generating 7, 124,251-118436-0018,0,281,0, time cost: 0.063s
Generating 8, 248,6313-66125-0020,0,297,0, time cost: 0.063s
Generating 9, 329,84-121123-0014,0,287,0, time cost: 0.063s
Generating 10, 265,6345-64257-0012,0,280,0, time cost: 0.063s
Generating 11, 184,5536-43358-0012,0,337,0, time cost: 0.014s
Generating 12, 226,6295-244435-0003,0,323,0, time cost: 0.014s
Generating 13, 278,652-129742-0011,0,326,0, time cost: 0.014s
Generating 14, 239,6313-66125-0002,0,306,0, time cost: 0.014s
Generating 15, 98,2428-83699-0010,0,310,0, time cost: 0.014s
Generating 16, 84,2277-149874-0021,0,297,0, time cost: 0.014s
Generating 17, 242,6313-66125-0006,0,299,0, time cost: 0.014s
Generating 18, 311,8297-275154-0015,0,320,0, time cost: 0.014s
Generating 19, 105,2428-83699-0026,0,312,0, time cost: 0.014s
Generating 20, 121,251-118436-0010,0,323,0, time cost: 0.014s
Generating 21, 62,2035-147960-0006,0,330,0, time cost: 0.014s
Generating 22, 164,3752-4943-0015,0,294,0, time cost: 0.014s
Generating 23, 15,1462-170138-0015,0,336,0, time cost: 0.014s
Generating 24, 201,5895-34615-0008,0,304,0, time cost: 0.014s
Generating 25, 99,2428-83699-0013,0,327,0, time cost: 0.014s
Generating 26, 107,2428-83699-0032,0,316,0, time cost: 0.014s
Generating 27, 268,6345-64257-0017,0,281,0, time cost: 0.014s
Generating 28, 39,1988-147956-0013,0,287,0, time cost: 0.014s
Generating 29, 309,8297-275154-0013,0,312,0, time cost: 0.014s
Generating 30, 271,6345-64257-0020,0,284,0, time cost: 0.014s
Generating 31, 170,3752-4943-0023,0,304,0, time cost: 0.014s
Generating 32, 51,1993-147149-0010,0,326,0, time cost: 0.014s
Generating 33, 241,6313-66125-0004,0,324,0, time cost: 0.014s
Generating 34, 86,2412-153947-0001,0,321,0, time cost: 0.014s
Generating 35, 287,7976-105575-0002,0,303,0, time cost: 0.014s
Generating 36, 78,2277-149874-0013,0,314,0, time cost: 0.014s
Generating 37, 222,6241-61943-0019,0,289,0, time cost: 0.014s
Generating 38, 330,84-121123-0015,0,302,0, time cost: 0.014s
Generating 39, 211,6241-61943-0001,0,320,0, time cost: 0.014s
Generating 40, 196,5895-34615-0000,0,332,0, time cost: 0.014s
Generating 41, 57,2035-147960-0001,0,391,0, time cost: 0.017s
Generating 42, 232,6295-244435-0024,0,418,0, time cost: 0.017s
Generating 43, 150,3536-23268-0015,0,393,0, time cost: 0.017s
Generating 44, 129,2803-154320-0002,0,351,0, time cost: 0.017s
Generating 45, 172,3752-4943-0026,0,403,0, time cost: 0.017s
Generating 46, 177,5338-24615-0009,0,424,0, time cost: 0.017s
Generating 47, 134,2803-154320-0008,0,357,0, time cost: 0.017s
Generating 48, 246,6313-66125-0014,0,377,0, time cost: 0.017s
Generating 49, 290,7976-105575-0009,0,403,0, time cost: 0.017s
Generating 50, 178,5338-24615-0010,0,387,0, time cost: 0.017s
Generating 51, 283,652-129742-0017,0,339,0, time cost: 0.017s
Generating 52, 257,6319-275224-0012,0,410,0, time cost: 0.017s
Generating 53, 149,3536-23268-0014,0,348,0, time cost: 0.017s
Generating 54, 321,84-121123-0001,0,397,0, time cost: 0.017s
Generating 55, 312,8297-275154-0017,0,368,0, time cost: 0.017s
Generating 56, 281,652-129742-0014,0,393,0, time cost: 0.017s
Generating 57, 66,2035-147960-0012,0,424,0, time cost: 0.017s
Generating 58, 162,3752-4943-0012,0,338,0, time cost: 0.017s
Generating 59, 63,2035-147960-0009,0,348,0, time cost: 0.017s
Generating 60, 35,1988-147956-0005,0,345,0, time cost: 0.017s
Generating 61, 235,6295-244435-0034,0,340,0, time cost: 0.017s
Generating 62, 126,251-118436-0021,0,396,0, time cost: 0.017s
Generating 63, 264,6345-64257-0010,0,397,0, time cost: 0.017s
Generating 64, 136,2803-154320-0011,0,426,0, time cost: 0.017s
Generating 65, 308,8297-275154-0008,0,402,0, time cost: 0.017s
Generating 66, 301,7976-105575-0026,0,353,0, time cost: 0.017s
Generating 67, 115,251-118436-0001,0,371,0, time cost: 0.017s
Generating 68, 135,2803-154320-0010,0,399,0, time cost: 0.017s
Generating 69, 140,2902-9006-0004,0,378,0, time cost: 0.017s
Generating 70, 217,6241-61943-0009,0,383,0, time cost: 0.017s
Generating 71, 214,6241-61943-0004,0,339,0, time cost: 0.017s
Generating 72, 141,2902-9006-0006,0,398,0, time cost: 0.017s
Generating 73, 316,8297-275154-0024,0,365,0, time cost: 0.017s
Generating 74, 277,652-129742-0010,0,338,0, time cost: 0.017s
Generating 75, 218,6241-61943-0011,0,388,0, time cost: 0.017s
Generating 76, 42,1988-147956-0018,0,352,0, time cost: 0.017s
Generating 77, 189,5694-64025-0007,0,390,0, time cost: 0.017s
Generating 78, 331,84-121123-0018,0,353,0, time cost: 0.017s
Generating 79, 60,2035-147960-0004,0,415,0, time cost: 0.017s
Generating 80, 160,3752-4943-0009,0,358,0, time cost: 0.017s
Generating 81, 157,3752-4943-0003,0,623,0, time cost: 0.031s
Generating 82, 48,1993-147149-0000,0,670,0, time cost: 0.031s
Generating 83, 41,1988-147956-0017,0,628,0, time cost: 0.031s
Generating 84, 273,652-129742-0004,0,710,0, time cost: 0.031s
Generating 85, 302,7976-105575-0027,0,666,0, time cost: 0.031s
Generating 86, 27,174-168635-0006,0,655,0, time cost: 0.031s
Generating 87, 43,1988-147956-0020,0,676,0, time cost: 0.031s
Generating 88, 293,7976-105575-0014,0,747,0, time cost: 0.031s
Generating 89, 110,2428-83699-0037,0,638,0, time cost: 0.031s
Generating 90, 341,8842-302196-0009,0,704,0, time cost: 0.031s
Generating 91, 44,1988-147956-0022,0,752,0, time cost: 0.034s
Generating 92, 208,5895-34615-0019,0,684,0, time cost: 0.034s
Generating 93, 207,5895-34615-0017,0,734,0, time cost: 0.034s
Generating 94, 71,2277-149874-0003,0,768,0, time cost: 0.034s
Generating 95, 198,5895-34615-0003,0,659,0, time cost: 0.034s
Generating 96, 225,6241-61943-0024,0,734,0, time cost: 0.034s
Generating 97, 237,6295-244435-0036,0,720,0, time cost: 0.034s
Generating 98, 327,84-121123-0008,0,700,0, time cost: 0.034s
Generating 99, 75,2277-149874-0010,0,740,0, time cost: 0.034s
Generating 100, 270,6345-64257-0019,0,770,0, time cost: 0.034s
Generating 101, 256,6319-275224-0010,0,692,0, time cost: 0.029s
Generating 102, 83,2277-149874-0020,0,736,0, time cost: 0.029s
Generating 103, 336,8842-302196-0002,0,664,0, time cost: 0.029s
Generating 104, 122,251-118436-0014,0,667,0, time cost: 0.029s
Generating 105, 191,5694-64025-0011,0,701,0, time cost: 0.029s
Generating 106, 14,1462-170138-0013,0,700,0, time cost: 0.029s
Generating 107, 114,2428-83699-0042,0,641,0, time cost: 0.029s
Generating 108, 289,7976-105575-0008,0,717,0, time cost: 0.029s
Generating 109, 119,251-118436-0008,0,621,0, time cost: 0.029s
Generating 110, 8,1272-128104-0013,0,708,0, time cost: 0.029s
Generating 111, 305,8297-275154-0004,0,664,0, time cost: 0.033s
Generating 112, 116,251-118436-0002,0,695,0, time cost: 0.033s
Generating 113, 210,6241-61943-0000,0,693,0, time cost: 0.033s
Generating 114, 61,2035-147960-0005,0,657,0, time cost: 0.033s
Generating 115, 322,84-121123-0003,0,678,0, time cost: 0.033s
Generating 116, 87,2412-153947-0002,0,658,0, time cost: 0.033s
Generating 117, 45,1988-147956-0026,0,690,0, time cost: 0.033s
Generating 118, 334,84-121123-0025,0,624,0, time cost: 0.033s
Generating 119, 152,3536-23268-0018,0,757,0, time cost: 0.033s
Generating 120, 72,2277-149874-0005,0,635,0, time cost: 0.033s
Generating 121, 206,5895-34615-0014,0,514,0, time cost: 0.024s
Generating 122, 161,3752-4943-0010,0,506,0, time cost: 0.024s
Generating 123, 0,1272-128104-0000,0,584,0, time cost: 0.024s
Generating 124, 77,2277-149874-0012,0,506,0, time cost: 0.024s
Generating 125, 325,84-121123-0006,0,560,0, time cost: 0.024s
Generating 126, 6,1272-128104-0010,0,558,0, time cost: 0.024s
Generating 127, 4,1272-128104-0006,0,562,0, time cost: 0.024s
Generating 128, 299,7976-105575-0022,0,536,0, time cost: 0.024s
Generating 129, 280,652-129742-0013,0,558,0, time cost: 0.024s
Generating 130, 247,6313-66125-0017,0,505,0, time cost: 0.024s
Generating 131, 169,3752-4943-0022,0,518,0, time cost: 0.025s
Generating 132, 231,6295-244435-0018,0,531,0, time cost: 0.025s
Generating 133, 163,3752-4943-0013,0,552,0, time cost: 0.025s
Generating 134, 288,7976-105575-0005,0,554,0, time cost: 0.025s
Generating 135, 342,8842-302196-0012,0,561,0, time cost: 0.025s
Generating 136, 219,6241-61943-0012,0,584,0, time cost: 0.025s
Generating 137, 37,1988-147956-0009,0,514,0, time cost: 0.025s
Generating 138, 16,1462-170138-0017,0,619,0, time cost: 0.025s
Generating 139, 337,8842-302196-0004,0,572,0, time cost: 0.025s
Generating 140, 339,8842-302196-0007,0,620,0, time cost: 0.025s
Generating 141, 59,2035-147960-0003,0,582,0, time cost: 0.024s
Generating 142, 263,6345-64257-0004,0,603,0, time cost: 0.024s
Generating 143, 36,1988-147956-0007,0,585,0, time cost: 0.024s
Generating 144, 252,6313-66125-0025,0,530,0, time cost: 0.024s
Generating 145, 340,8842-302196-0008,0,529,0, time cost: 0.024s
Generating 146, 118,251-118436-0005,0,529,0, time cost: 0.024s
Generating 147, 97,2428-83699-0007,0,569,0, time cost: 0.024s
Generating 148, 74,2277-149874-0008,0,537,0, time cost: 0.024s
Generating 149, 186,5536-43358-0015,0,594,0, time cost: 0.024s
Generating 150, 260,6319-275224-0019,0,576,0, time cost: 0.024s
Generating 151, 221,6241-61943-0017,0,607,0, time cost: 0.028s
Generating 152, 139,2803-154320-0014,0,527,0, time cost: 0.028s
Generating 153, 192,5694-64025-0015,0,505,0, time cost: 0.028s
Generating 154, 47,1988-147956-0028,0,586,0, time cost: 0.028s
Generating 155, 96,2412-153947-0016,0,517,0, time cost: 0.028s
Generating 156, 171,3752-4943-0024,0,564,0, time cost: 0.028s
Generating 157, 17,1462-170138-0022,0,617,0, time cost: 0.028s
Generating 158, 284,652-129742-0018,0,546,0, time cost: 0.028s
Generating 159, 267,6345-64257-0016,0,576,0, time cost: 0.028s
Generating 160, 292,7976-105575-0012,0,514,0, time cost: 0.028s
Generating 161, 183,5536-43358-0010,0,812,0, time cost: 0.042s
Generating 162, 203,5895-34615-0010,0,775,0, time cost: 0.042s
Generating 163, 209,5895-34615-0020,0,951,0, time cost: 0.042s
Generating 164, 31,174-168635-0019,0,798,0, time cost: 0.042s
Generating 165, 88,2412-153947-0004,0,870,0, time cost: 0.042s
Generating 166, 250,6313-66125-0023,0,933,0, time cost: 0.042s
Generating 167, 91,2412-153947-0009,0,870,0, time cost: 0.042s
Generating 168, 64,2035-147960-0010,0,957,0, time cost: 0.042s
Generating 169, 28,174-168635-0012,0,834,0, time cost: 0.042s
Generating 170, 155,3752-4943-0000,0,881,0, time cost: 0.042s
Generating 171, 104,2428-83699-0025,0,799,0, time cost: 0.038s
Generating 172, 153,3536-23268-0026,0,881,0, time cost: 0.038s
Generating 173, 272,652-129742-0001,0,864,0, time cost: 0.038s
Generating 174, 319,8297-275154-0027,0,873,0, time cost: 0.038s
Generating 175, 5,1272-128104-0007,0,922,0, time cost: 0.038s
Generating 176, 18,1462-170138-0023,0,948,0, time cost: 0.038s
Generating 177, 34,1988-147956-0004,0,901,0, time cost: 0.038s
Generating 178, 181,5536-43358-0007,0,940,0, time cost: 0.038s
Generating 179, 195,5694-64025-0019,0,885,0, time cost: 0.038s
Generating 180, 112,2428-83699-0040,0,781,0, time cost: 0.038s
Generating 181, 58,2035-147960-0002,0,882,0, time cost: 0.037s
Generating 182, 279,652-129742-0012,0,927,0, time cost: 0.037s
Generating 183, 147,3536-23268-0007,0,919,0, time cost: 0.037s
Generating 184, 108,2428-83699-0034,0,810,0, time cost: 0.037s
Generating 185, 262,6345-64257-0003,0,876,0, time cost: 0.037s
Generating 186, 120,251-118436-0009,0,894,0, time cost: 0.037s
Generating 187, 82,2277-149874-0019,0,843,0, time cost: 0.037s
Generating 188, 230,6295-244435-0017,0,853,0, time cost: 0.037s
Generating 189, 79,2277-149874-0014,0,858,0, time cost: 0.037s
Generating 190, 228,6295-244435-0009,0,825,0, time cost: 0.037s
Generating 191, 274,652-129742-0006,0,910,0, time cost: 0.038s
Generating 192, 46,1988-147956-0027,0,771,0, time cost: 0.038s
Generating 193, 21,1673-143396-0002,0,783,0, time cost: 0.038s
Generating 194, 90,2412-153947-0007,0,872,0, time cost: 0.038s
Generating 195, 3,1272-128104-0005,0,899,0, time cost: 0.038s
Generating 196, 123,251-118436-0016,0,895,0, time cost: 0.038s
Generating 197, 213,6241-61943-0003,0,781,0, time cost: 0.038s
Generating 198, 49,1993-147149-0001,0,952,0, time cost: 0.038s
Generating 199, 13,1462-170138-0010,0,860,0, time cost: 0.038s
Generating 200, 56,2035-147960-0000,0,900,0, time cost: 0.038s
Generating 201, 269,6345-64257-0018,0,477,0, time cost: 0.020s
Generating 202, 215,6241-61943-0005,0,488,0, time cost: 0.020s
Generating 203, 314,8297-275154-0020,0,445,0, time cost: 0.020s
Generating 204, 243,6313-66125-0007,0,491,0, time cost: 0.020s
Generating 205, 81,2277-149874-0018,0,500,0, time cost: 0.020s
Generating 206, 333,84-121123-0023,0,467,0, time cost: 0.020s
Generating 207, 179,5338-24615-0012,0,428,0, time cost: 0.020s
Generating 208, 148,3536-23268-0009,0,430,0, time cost: 0.020s
Generating 209, 20,1462-170138-0027,0,499,0, time cost: 0.020s
Generating 210, 32,174-168635-0022,0,432,0, time cost: 0.020s
Generating 211, 234,6295-244435-0031,0,473,0, time cost: 0.024s
Generating 212, 318,8297-275154-0026,0,487,0, time cost: 0.024s
Generating 213, 307,8297-275154-0007,0,447,0, time cost: 0.024s
Generating 214, 80,2277-149874-0015,0,471,0, time cost: 0.024s
Generating 215, 275,652-129742-0007,0,487,0, time cost: 0.024s
Generating 216, 317,8297-275154-0025,0,486,0, time cost: 0.024s
Generating 217, 102,2428-83699-0020,0,487,0, time cost: 0.024s
Generating 218, 240,6313-66125-0003,0,456,0, time cost: 0.024s
Generating 219, 109,2428-83699-0036,0,458,0, time cost: 0.024s
Generating 220, 38,1988-147956-0012,0,455,0, time cost: 0.024s
Generating 221, 205,5895-34615-0013,0,473,0, time cost: 0.020s
Generating 222, 251,6313-66125-0024,0,439,0, time cost: 0.020s
Generating 223, 224,6241-61943-0023,0,434,0, time cost: 0.020s
Generating 224, 65,2035-147960-0011,0,436,0, time cost: 0.020s
Generating 225, 323,84-121123-0004,0,438,0, time cost: 0.020s
Generating 226, 101,2428-83699-0019,0,489,0, time cost: 0.020s
Generating 227, 258,6319-275224-0013,0,485,0, time cost: 0.020s
Generating 228, 131,2803-154320-0005,0,475,0, time cost: 0.020s
Generating 229, 138,2803-154320-0013,0,435,0, time cost: 0.020s
Generating 230, 168,3752-4943-0020,0,486,0, time cost: 0.020s
Generating 231, 70,2035-147960-0016,0,488,0, time cost: 0.020s
Generating 232, 133,2803-154320-0007,0,449,0, time cost: 0.020s
Generating 233, 29,174-168635-0014,0,481,0, time cost: 0.020s
Generating 234, 298,7976-105575-0021,0,464,0, time cost: 0.020s
Generating 235, 291,7976-105575-0010,0,451,0, time cost: 0.020s
Generating 236, 300,7976-105575-0023,0,476,0, time cost: 0.020s
Generating 237, 296,7976-105575-0018,0,427,0, time cost: 0.020s
Generating 238, 249,6313-66125-0021,0,496,0, time cost: 0.020s
Generating 239, 68,2035-147960-0014,0,445,0, time cost: 0.020s
Generating 240, 188,5694-64025-0003,0,490,0, time cost: 0.020s
Generating 241, 146,3536-23268-0002,0,1048,0, time cost: 0.059s
Generating 242, 95,2412-153947-0015,0,1101,0, time cost: 0.059s
Generating 243, 303,8297-275154-0000,0,1020,0, time cost: 0.059s
Generating 244, 261,6319-275224-0020,0,1192,0, time cost: 0.059s
Generating 245, 145,2902-9006-0019,0,1421,0, time cost: 0.059s
Generating 246, 173,5338-24615-0000,0,1001,0, time cost: 0.059s
Generating 247, 158,3752-4943-0004,0,1399,0, time cost: 0.059s
Generating 248, 127,2803-154320-0000,0,1146,0, time cost: 0.059s
Generating 249, 180,5536-43358-0006,0,1039,0, time cost: 0.059s
Generating 250, 1,1272-128104-0002,0,1247,0, time cost: 0.059s
Generating 251, 185,5536-43358-0013,0,1038,0, time cost: 0.058s
Generating 252, 304,8297-275154-0002,0,974,0, time cost: 0.058s
Generating 253, 187,5694-64025-0002,0,1094,0, time cost: 0.058s
Generating 254, 137,2803-154320-0012,0,979,0, time cost: 0.058s
Generating 255, 156,3752-4943-0001,0,1106,0, time cost: 0.058s
Generating 256, 154,3536-23268-0027,0,1030,0, time cost: 0.058s
Generating 257, 294,7976-105575-0016,0,1019,0, time cost: 0.058s
Generating 258, 89,2412-153947-0006,0,1166,0, time cost: 0.058s
Generating 259, 143,2902-9006-0009,0,1195,0, time cost: 0.058s
Generating 260, 33,1988-147956-0001,0,1419,0, time cost: 0.058s
Generating 261, 276,652-129742-0009,0,1395,0, time cost: 0.058s
Generating 262, 130,2803-154320-0004,0,1199,0, time cost: 0.058s
Generating 263, 26,174-168635-0004,0,1275,0, time cost: 0.058s
Generating 264, 2,1272-128104-0003,0,988,0, time cost: 0.058s
Generating 265, 94,2412-153947-0014,0,1278,0, time cost: 0.058s
Generating 266, 282,652-129742-0015,0,1179,0, time cost: 0.058s
Generating 267, 254,6319-275224-0001,0,1216,0, time cost: 0.058s
Generating 268, 117,251-118436-0003,0,1100,0, time cost: 0.058s
Generating 269, 54,1993-147149-0028,0,1015,0, time cost: 0.058s
Generating 270, 142,2902-9006-0008,0,1106,0, time cost: 0.058s
Generating 271, 259,6319-275224-0014,0,1071,0, time cost: 0.054s
Generating 272, 176,5338-24615-0007,0,1006,0, time cost: 0.054s
Generating 273, 125,251-118436-0019,0,1146,0, time cost: 0.054s
Generating 274, 12,1462-170138-0005,0,1315,0, time cost: 0.054s
Generating 275, 229,6295-244435-0016,0,1149,0, time cost: 0.054s
Generating 276, 193,5694-64025-0016,0,1070,0, time cost: 0.054s
Generating 277, 151,3536-23268-0016,0,1130,0, time cost: 0.054s
Generating 278, 92,2412-153947-0011,0,1011,0, time cost: 0.054s
Generating 279, 204,5895-34615-0012,0,1032,0, time cost: 0.054s
Generating 280, 227,6295-244435-0004,0,1230,0, time cost: 0.054s
Generating 281, 132,2803-154320-0006,0,216,0, time cost: 0.016s
Generating 282, 285,652-129742-0019,0,277,0, time cost: 0.016s
Generating 283, 320,84-121123-0000,0,207,0, time cost: 0.016s
Generating 284, 233,6295-244435-0027,0,240,0, time cost: 0.016s
Generating 285, 100,2428-83699-0014,0,220,0, time cost: 0.016s
Generating 286, 306,8297-275154-0005,0,276,0, time cost: 0.016s
Generating 287, 73,2277-149874-0006,0,273,0, time cost: 0.016s
Generating 288, 295,7976-105575-0017,0,192,0, time cost: 0.016s
Generating 289, 244,6313-66125-0009,0,269,0, time cost: 0.016s
Generating 290, 111,2428-83699-0039,0,196,0, time cost: 0.016s
Generating 291, 238,6313-66125-0000,0,234,0, time cost: 0.011s
Generating 292, 245,6313-66125-0012,0,227,0, time cost: 0.011s
Generating 293, 315,8297-275154-0023,0,258,0, time cost: 0.011s
Generating 294, 166,3752-4943-0017,0,226,0, time cost: 0.011s
Generating 295, 85,2412-153947-0000,0,253,0, time cost: 0.011s
Generating 296, 332,84-121123-0022,0,259,0, time cost: 0.011s
Generating 297, 202,5895-34615-0009,0,276,0, time cost: 0.011s
Generating 298, 19,1462-170138-0026,0,237,0, time cost: 0.011s
Generating 299, 69,2035-147960-0015,0,154,0, time cost: 0.011s
Generating 300, 9,1272-128104-0014,0,223,0, time cost: 0.011s
Generating 301, 93,2412-153947-0012,0,196,0, time cost: 0.011s
Generating 302, 103,2428-83699-0021,0,280,0, time cost: 0.011s
Generating 303, 200,5895-34615-0006,0,251,0, time cost: 0.011s
Generating 304, 212,6241-61943-0002,0,272,0, time cost: 0.011s
Generating 305, 223,6241-61943-0021,0,250,0, time cost: 0.011s
Generating 306, 165,3752-4943-0016,0,247,0, time cost: 0.011s
Generating 307, 326,84-121123-0007,0,198,0, time cost: 0.011s
Generating 308, 297,7976-105575-0020,0,207,0, time cost: 0.011s
Generating 309, 113,2428-83699-0041,0,205,0, time cost: 0.011s
Generating 310, 216,6241-61943-0007,0,262,0, time cost: 0.011s
Generating 311, 11,1462-170138-0003,0,230,0, time cost: 0.011s
Generating 312, 40,1988-147956-0014,0,217,0, time cost: 0.011s
Generating 313, 286,7976-105575-0001,0,278,0, time cost: 0.011s
Generating 314, 328,84-121123-0013,0,238,0, time cost: 0.011s
Generating 315, 194,5694-64025-0018,0,267,0, time cost: 0.011s
Generating 316, 220,6241-61943-0015,0,247,0, time cost: 0.011s
Generating 317, 76,2277-149874-0011,0,245,0, time cost: 0.011s
Generating 318, 167,3752-4943-0019,0,248,0, time cost: 0.011s
Generating 319, 313,8297-275154-0018,0,219,0, time cost: 0.011s
Generating 320, 67,2035-147960-0013,0,266,0, time cost: 0.011s
Generating 321, 10,1462-170138-0000,0,1453,0, time cost: 0.130s
Generating 322, 324,84-121123-0005,0,1594,0, time cost: 0.130s
Generating 323, 335,8842-302196-0000,0,1463,0, time cost: 0.130s
Generating 324, 144,2902-9006-0018,0,3203,0, time cost: 0.130s
Generating 325, 253,6313-66125-0027,0,1445,0, time cost: 0.130s
Generating 326, 182,5536-43358-0008,0,2037,0, time cost: 0.130s
Generating 327, 128,2803-154320-0001,0,1554,0, time cost: 0.130s
Generating 328, 175,5338-24615-0005,0,1775,0, time cost: 0.130s
Generating 329, 24,1673-143396-0012,0,1445,0, time cost: 0.130s
Generating 330, 199,5895-34615-0004,0,1593,0, time cost: 0.130s
Generating 331, 55,1993-147149-0030,0,1550,0, time cost: 0.093s
Generating 332, 255,6319-275224-0008,0,1843,0, time cost: 0.093s
Generating 333, 25,1673-143396-0016,0,1444,0, time cost: 0.093s
Generating 334, 50,1993-147149-0003,0,1428,0, time cost: 0.093s
Generating 335, 53,1993-147149-0022,0,1652,0, time cost: 0.093s
Generating 336, 23,1673-143396-0009,0,1644,0, time cost: 0.093s
Generating 337, 338,8842-302196-0005,0,2343,0, time cost: 0.093s
Generating 338, 310,8297-275154-0014,0,1807,0, time cost: 0.093s
Generating 339, 190,5694-64025-0010,0,2160,0, time cost: 0.093s
Generating 340, 7,1272-128104-0011,0,1510,0, time cost: 0.093s
local/vc/am_pytorch/01_gen.sh: line 58: 80718 Segmentation fault      (core dumped) python ${proj_dir}/main.py --inference --module-config ${config_file} --cudnn-deterministic-toggle --batch-size ${batch_size} --num-workers ${batch_size} --sampler block_shuffle_by_length --cudnn-benchmark-toggle --ignore-cached-file-infor --output-dir ${output_dir} --trained-model ${TEMP_ACOUSTIC_NETWORK_PATH}


**** Is this a data problem?

Der erste:
find . -iname "*2428-83699-0031*"
./exp/am_nsf_data/libri_dev_enrolls/f0/2428-83699-0031.f0
./exp/am_nsf_data/libri_dev_enrolls/ppg/2428-83699-0031.ppg
./exp/am_nsf_data/libri_dev_enrolls/am_pt_out_mel/2428-83699-0031.mel
./exp/am_nsf_data/libri_dev_enrolls/xvector/2428-83699-0031.xvector
./data/libri_dev_enrolls/yaapt_pitch/2428-83699-0031.f0
./data/libri_dev/wav/2428-83699-0031
./data/libri_dev/wav/2428-83699-0031/2428-83699-0031.wav


Der wo das segfaulting auftritt:

find . -iname "*1272-128104-0011*"
./exp/am_nsf_data/libri_dev_enrolls/f0/1272-128104-0011.f0
./exp/am_nsf_data/libri_dev_enrolls/ppg/1272-128104-0011.ppg
./exp/am_nsf_data/libri_dev_enrolls/am_pt_out_mel/1272-128104-0011.mel
./exp/am_nsf_data/libri_dev_enrolls/xvector/1272-128104-0011.xvector
./data/libri_dev_enrolls/yaapt_pitch/1272-128104-0011.f0
./data/libri_dev/wav/1272-128104-0011
./data/libri_dev/wav/1272-128104-0011/1272-128104-0011.wav









* Links

Dieses README
/data/work3/cgeng/Voice-Privacy-Challenge-2022/nii_scripts/waveform-modeling/project-WaveNet/README


sidekit: https://projets-lium.univ-lemans.fr/sidekit/index.html
