
* ap-cgeng.fritz.box

** install.sh
*** nvidia toolkit

#+begin_src bash
apt-cache rdepends packagename nvidia-cuda-toolkit
#+end_src

#+RESULTS:
| nvidia-cuda-toolkit     |          |
| Reverse                 | Depends: |
| nvidia-cuda-toolkit-gcc |          |
| python3-pycuda          |          |
| nvidia-profiler         |          |
| hxtools                 |          |
| libthrust-dev           |          |
| python3-theano          |          |
| python3-numba           |          |
| nvptx-tools             |          |


#+begin_src  bash :results output raw
 sudo  apt install -y nvidia-cuda-toolkit
#+end_src


#+RESULTS:
sudo  apt install -y nvidia-cuda-toolkit
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  cpp-8 g++-8 gcc-8 gcc-8-base libaccinj64-10.1 libcublas10 libcublaslt10 libcudart10.1 libcufft10 libcufftw10 libcuinj64-10.1 libcupti-dev libcupti-doc libcupti10.1 libcurand10 libcusolver10
  libcusolvermg10 libcusparse10 libgcc-8-dev libmpx2 libncurses5 libnppc10 libnppial10 libnppicc10 libnppicom10 libnppidei10 libnppif10 libnppig10 libnppim10 libnppist10 libnppisu10 libnppitc10
  libnpps10 libnvblas10 libnvgraph10 libnvidia-ml-dev libnvjpeg10 libnvrtc10.1 libnvtoolsext1 libnvvm3 libstdc++-8-dev libthrust-dev libtinfo5 libvdpau-dev node-html5shiv nsight-compute nsight-systems
  nvidia-cuda-dev nvidia-cuda-doc nvidia-cuda-gdb nvidia-opencl-dev nvidia-profiler nvidia-visual-profiler ocl-icd-opencl-dev opencl-c-headers openjdk-8-jre openjdk-8-jre-headless
Suggested packages:
  gcc-8-locales g++-8-multilib gcc-8-doc gcc-8-multilib libstdc++-8-doc libvdpau-doc nodejs nvidia-driver | nvidia-tesla-440-driver | nvidia-tesla-418-driver libpoclu-dev fonts-ipafont-gothic
  fonts-ipafont-mincho fonts-wqy-microhei fonts-wqy-zenhei
Recommended packages:
  libnvcuvid1
The following NEW packages will be installed:
  cpp-8 g++-8 gcc-8 gcc-8-base libaccinj64-10.1 libcublas10 libcublaslt10 libcudart10.1 libcufft10 libcufftw10 libcuinj64-10.1 libcupti-dev libcupti-doc libcupti10.1 libcurand10 libcusolver10
  libcusolvermg10 libcusparse10 libgcc-8-dev libmpx2 libncurses5 libnppc10 libnppial10 libnppicc10 libnppicom10 libnppidei10 libnppif10 libnppig10 libnppim10 libnppist10 libnppisu10 libnppitc10
  libnpps10 libnvblas10 libnvgraph10 libnvidia-ml-dev libnvjpeg10 libnvrtc10.1 libnvtoolsext1 libnvvm3 libstdc++-8-dev libthrust-dev libtinfo5 libvdpau-dev node-html5shiv nsight-compute nsight-systems
  nvidia-cuda-dev nvidia-cuda-doc nvidia-cuda-gdb nvidia-cuda-toolkit nvidia-opencl-dev nvidia-profiler nvidia-visual-profiler ocl-icd-opencl-dev opencl-c-headers openjdk-8-jre openjdk-8-jre-headless
0 upgraded, 58 newly installed, 0 to remove and 15 not upgraded.
Need to get 1.355 MB/1.428 MB of archives.
After this operation, 3.819 MB of additional disk space will be used.





*** Chose compiler

#+begin_exampple bash
history | grep alternatives | grep -v   "#"
#+end_example

#+RESULTS:
2013  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8
2014  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9
2017  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 8
2018  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 9
2020  sudo update-alternatives --config gcc
2021  sudo update-alternatives --config g++





* Compute3
** My Seg Fault in baseline/run.sh local/main_anonymization.sh

in baseline:
 source env.sh
 local/main_anonymization.sh

Mein Aufruf
#local/main_anonymization.sh

# das hier ist der Zwischenschritt:
/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/local/anon/anonymize_data_dir.sh

Der Fehler selbst tritt auf in:
local/vc/am_pytorch/01_gen.sh


Der Aufruf der direkt zum Fehler Führt ist:
File: baseline/local/vc/am_pytorch/01_angen.sh
50:1:python ${proj_dir}/main.py --inference --module-config ${config_file} \



*** Call Hierarchy

local/main_anonymization.sh -> local/anon/anonymize_data_dir.sh ->  local/vc/am_pytorch/01_gen.sh

*** Aufruf von =local/anon/anonymize_data_dir.sh= in main_anonymization

    printf "${GREEN}\n Anonymizing using x-vectors and neural wavform models...${NC}\n"
    ppg_dir=${ppg_model}/nnet3_cleaned
    local/anon/anonymize_data_dir.sh \
      --nj $nj --anoni-pool $anoni_pool \
      --data-netcdf $data_netcdf \
      --ppg-model $ppg_model --ppg-dir $ppg_dir \
      --xvec-nnet-dir $xvec_nnet_dir \
      --anon-xvec-out-dir $anon_xvec_out_dir --plda-dir $xvec_nnet_dir \
      --pseudo-xvec-rand-level $anon_level --distance $distance \
      --proximity $proximity --cross-gender $cross_gender \
      --rand-seed $rand_seed \
      --anon-data-suffix $anon_data_suffix \
      --model-type $tts_type \
      --inference-trunc-len $inference_trunc_len \
      --inference-batch-size-am $inference_batch_size_am \
      --inference-batch-size-wav $inference_batch_size_wav \
      $dset



*** logs


#+begin_example
Generating 338, 310,8297-275154-0014,0,1807,0, time cost: 0.095s
Generating 339, 190,5694-64025-0010,0,2160,0, time cost: 0.095s
Generating 340, 7,1272-128104-0011,0,1510,0, time cost: 0.095s
local/vc/am_pytorch/01_gen.sh: line 50: 56543 Segmentation fault      (core dumped) python ${proj_dir}/main.py --inference --module-config ${config_file} --cudnn-deterministic-toggle --batch-size ${batch_size} --num-workers ${batch_size} --sampler block_shuffle_by_length --cudnn-benchmark-toggle --ignore-cached-file-infor --output-dir ${output_dir} --trained-model ${TEMP_ACOUSTIC_NETWORK_PATH}
(base) cgeng@compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline$ utils/combine_data.sh
utils/combine_data.sh
Usage: combine_data.sh [--extra-files 'file1 file2'] <dest-data-dir> <src-data-dir1> <src-data-dir2> ...
Note, files that don't appear in all source dirs will not be combined,
with the exception of utt2uniq and segments, which are created where necessary.
(base) cgeng@compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline$ #local/main_anonymization.sh
(base) cgeng@compute3:/data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline$
#+end_example

*** More logs from /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/local/anon/anonymize_data_dir.sh



**** Stage a.0: Extracting xvectors for libri_dev_enrolls.
steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config conf/mfcc.conf --nj 16 --cmd run.pl data/libri_dev_enrolls exp/make_mfcc /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/mfcc
steps/make_mfcc.sh: moving data/libri_dev_enrolls/feats.scp to data/libri_dev_enrolls/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libri_dev_enrolls
fix_data_dir.sh: kept all 343 utterances.
fix_data_dir.sh: old files are kept in data/libri_dev_enrolls/.backup
sid/compute_vad_decision.sh --nj 16 --cmd run.pl data/libri_dev_enrolls exp/make_vad /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/mfcc
sid/compute_vad_decision.sh: moving data/libri_dev_enrolls/vad.scp to data/libri_dev_enrolls/.backup
Created VAD output for libri_dev_enrolls
fix_data_dir.sh: kept all 343 utterances.
fix_data_dir.sh: old files are kept in data/libri_dev_enrolls/.backup
sid/nnet3/xvector/extract_xvectors.sh --cmd run.pl --nj 16 exp/models/2_xvect_extr/exp/xvector_nnet_1a data/libri_dev_enrolls exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls
sid/nnet3/xvector/extract_xvectors.sh: using exp/models/2_xvect_extr/exp/xvector_nnet_1a/extract.config to extract xvectors
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors for data/libri_dev_enrolls
sid/nnet3/xvector/extract_xvectors.sh: extracting xvectors from nnet
sid/nnet3/xvector/extract_xvectors.sh: combining xvectors across jobs
sid/nnet3/xvector/extract_xvectors.sh: computing mean of xvectors for each speaker

**** Stage a.1: Generating pseudo-speakers for libri_dev_enrolls.
Computing PLDA affinity scores of each source speaker to each pool speaker.
['local/anon/gen_pseudo_xvecs.py', 'data/libri_dev_enrolls', 'data/libritts_train_other_500', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/spk_pool_scores', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon', 'exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/pseudo_xvecs', 'spk', 'false', 'farthest', '0']
**Same gender speakers will be selected.**
Randomization level: spk
Proximity: farthest
Reading source spk2gender.
Reading source spk2utt.
Reading pool spk2gender.
Reading pool xvectors.
Read  1160 pool xvectors
Writing pseud-speaker xvectors to: exp/models/2_xvect_extr/exp/xvector_nnet_1a/anon/xvectors_libri_dev_enrolls/pseudo_xvecs
Writing pseudo-speaker spk2gender.
f0_download=true, data_dir=libri_dev_enrolls

**** Stage a.2: Pitch extraction for libri_dev_enrolls.
local/featex/make_pitch.sh --nj 16 --cmd run.pl data/libri_dev_enrolls exp/make_pitch data/libri_dev_enrolls/pitch
local/featex/make_pitch.sh: moving data/libri_dev_enrolls/pitch.scp to data/libri_dev_enrolls/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls
local/featex/make_pitch.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
time for yaapt

**** Stage a.3: PPG extraction for libri_dev_enrolls.
utils/copy_data_dir.sh: copied data from data/libri_dev_enrolls to data/libri_dev_enrolls_hires
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls_hires
steps/make_mfcc.sh --nj 16 --mfcc-config conf/mfcc_hires.conf --cmd run.pl data/libri_dev_enrolls_hires
steps/make_mfcc.sh: moving data/libri_dev_enrolls_hires/feats.scp to data/libri_dev_enrolls_hires/.backup
utils/validate_data_dir.sh: Successfully validated data-directory data/libri_dev_enrolls_hires
steps/make_mfcc.sh: [info]: no segments file exists: assuming wav.scp indexed by utterance.
steps/make_mfcc.sh: Succeeded creating MFCC features for libri_dev_enrolls_hires
steps/online/nnet2/extract_ivectors_online.sh --cmd run.pl --nj 16 data/libri_dev_enrolls_hires exp/models/1_asr_am/exp/nnet3_cleaned/extractor exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_enrolls_hires
steps/online/nnet2/extract_ivectors_online.sh: extracting iVectors
steps/online/nnet2/extract_ivectors_online.sh: combining iVectors across jobs
steps/online/nnet2/extract_ivectors_online.sh: done extracting (online) iVectors to exp/models/1_asr_am/exp/nnet3_cleaned/ivectors_libri_dev_enrolls_hires using the extractor in exp/models/1_asr_am/exp/nnet3_cleaned/extractor.
Done


**** Stage a.4: Make netcdf data for VC.
Writing SCP file..
Der ppg-file_ exp/models/1_asr_am/exp/nnet3_cleaned/ppg_libri_dev_enrolls/phone_post.scp
Writing PPG features /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/ppg
/data/work3/cgeng/Voice-Privacy-Challenge-2022/nii/pyTools/ioTools/readwrite.py:187: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  datatype = np.dtype((format,1))
Finished writing PPG feats.
Writing xvector and F0 for train.
false
false
/data/work3/cgeng/Voice-Privacy-Challenge-2022/nii/pyTools/ioTools/readwrite.py:187: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  datatype = np.dtype((format,1))

**** Stage a.5: Generate melspec from acoustic model for libri_dev_enrolls.
Etwas debug info für mich
proj_dir: /data/work3/cgeng/Voice-Privacy-Challenge-2022/nii_pytorch/projects/am
config_file: config
batch_size: 10
output_dir: /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/am_pt_out_mel
TEMP_ACOUSTIC_NETWORK_PATH: /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/models/3_ss_am_pt/trained_network.pt
-------------------------------------------------
---  Start program 2023-01-31 09:48:50.966738 ---
-------------------------------------------------
Load module: config
Load module: model
cudnn_deterministic set to False
cudnn_benchmark set to True
---------------------------------------------------------------------
---  Loading dataset libri_dev_enrolls 2023-01-31 09:48:51.424183 ---
---------------------------------------------------------------------
Get data statistis (may be slow due to data I/O)
------------------------------------------------>|
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Merge datasets by: concatenate
Dataset libri_dev_enrolls:
  Time steps: 227416
  Data sequence num: 343
  Maximum sequence length: 3203
  Minimum sequence length: 154
  Inputs
    Dirs:
        /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/ppg
        /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/xvector
        /data/work3/cgeng/Voice-Privacy-Challenge-2022/baseline/exp/am_nsf_data/libri_dev_enrolls/f0
    Exts:['.ppg', '.xvector', '.f0']
    Dims:[256, 512, 1]
    Reso:[1, 1, 1]
    Norm:[True, True, True]
  Outputs
    Dirs:
    Exts:['.mel']
    Dims:[80]
    Reso:[1]
    Norm:[True]
{'batch_size': 10, 'shuffle': True, 'num_workers': 10, 'sampler': 'block_shuffle_by_length'}

Use single GPU: GeForce GTX 1080 Ti

Model check:
[OK]: prepare_mean_std found
[OK]: normalize_input found
[OK]: normalize_target found
[OK]: denormalize_output found
[OK]: forward found
[OK]: use inference, alternative method for inference
[OK]: loss is ignored, loss defined within model module
[OK]: other_setups is ignored, other setup functions before training
[OK]: flag_validation is ignored, flag to indicate train or validation set
[OK]: validation is ignored, deprecated. Please use model.flag_validation
[OK]: finish_up_inference is ignored, method to finish up work after inference
Model check done

Model infor:
Model(
  (m_base): Sequential(
    (0): Linear(in_features=769, out_features=512, bias=True)
    (1): Tanh()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): Tanh()
    (4): LSTM(512, 128, batch_first=True, bidirectional=True)
  )
  (m_fdback): CombineFeedBack(
    (m_gate): GatedActWithNoise()
    (m_fb_trans): Sequential(
      (0): Linear(in_features=80, out_features=80, bias=True)
      (1): Linear(in_features=80, out_features=80, bias=True)
    )
  )
  (m_fb_proc): Sequential(
    (0): LSTMLayer(
      (m_lstm): LSTM(336, 512, batch_first=True)
    )
    (1): LSTMLayer(
      (m_lstm): LSTM(512, 512, batch_first=True)
    )
  )
  (m_fb_proc_out): Linear(in_features=512, out_features=80, bias=True)
  (m_post): PostNet(
    (m_post): Sequential(
      (0): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (1): GatedActWithNoise()
      (2): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (3): GatedActWithNoise()
      (4): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (5): GatedActWithNoise()
      (6): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
      (7): GatedActWithNoise()
      (8): PostNetCNNLayer(
        (m_cnn): Conv1d(80, 80, kernel_size=(5,), stride=(1,), padding=(4,))
      )
    )
  )
  (m_loss): MSELoss()
)
Parameter number: 5370752



Start inference (generation):
Generating 1, 106,2428-83699-0031,0,329,0, time cost: 0.063s
Generating 2, 52,1993-147149-0014,0,304,0, time cost: 0.063s
Generating 3, 236,6295-244435-0035,0,318,0, time cost: 0.063s
Generating 4, 266,6345-64257-0014,0,307,0, time cost: 0.063s
Generating 5, 159,3752-4943-0005,0,309,0, time cost: 0.063s
Generating 6, 197,5895-34615-0001,0,329,0, time cost: 0.063s
Generating 7, 124,251-118436-0018,0,281,0, time cost: 0.063s
Generating 8, 248,6313-66125-0020,0,297,0, time cost: 0.063s
Generating 9, 329,84-121123-0014,0,287,0, time cost: 0.063s
Generating 10, 265,6345-64257-0012,0,280,0, time cost: 0.063s
Generating 11, 184,5536-43358-0012,0,337,0, time cost: 0.014s
Generating 12, 226,6295-244435-0003,0,323,0, time cost: 0.014s
Generating 13, 278,652-129742-0011,0,326,0, time cost: 0.014s
Generating 14, 239,6313-66125-0002,0,306,0, time cost: 0.014s
Generating 15, 98,2428-83699-0010,0,310,0, time cost: 0.014s
Generating 16, 84,2277-149874-0021,0,297,0, time cost: 0.014s
Generating 17, 242,6313-66125-0006,0,299,0, time cost: 0.014s
Generating 18, 311,8297-275154-0015,0,320,0, time cost: 0.014s
Generating 19, 105,2428-83699-0026,0,312,0, time cost: 0.014s
Generating 20, 121,251-118436-0010,0,323,0, time cost: 0.014s
Generating 21, 62,2035-147960-0006,0,330,0, time cost: 0.014s
Generating 22, 164,3752-4943-0015,0,294,0, time cost: 0.014s
Generating 23, 15,1462-170138-0015,0,336,0, time cost: 0.014s
Generating 24, 201,5895-34615-0008,0,304,0, time cost: 0.014s
Generating 25, 99,2428-83699-0013,0,327,0, time cost: 0.014s
Generating 26, 107,2428-83699-0032,0,316,0, time cost: 0.014s
Generating 27, 268,6345-64257-0017,0,281,0, time cost: 0.014s
Generating 28, 39,1988-147956-0013,0,287,0, time cost: 0.014s
Generating 29, 309,8297-275154-0013,0,312,0, time cost: 0.014s
Generating 30, 271,6345-64257-0020,0,284,0, time cost: 0.014s
Generating 31, 170,3752-4943-0023,0,304,0, time cost: 0.014s
Generating 32, 51,1993-147149-0010,0,326,0, time cost: 0.014s
Generating 33, 241,6313-66125-0004,0,324,0, time cost: 0.014s
Generating 34, 86,2412-153947-0001,0,321,0, time cost: 0.014s
Generating 35, 287,7976-105575-0002,0,303,0, time cost: 0.014s
Generating 36, 78,2277-149874-0013,0,314,0, time cost: 0.014s
Generating 37, 222,6241-61943-0019,0,289,0, time cost: 0.014s
Generating 38, 330,84-121123-0015,0,302,0, time cost: 0.014s
Generating 39, 211,6241-61943-0001,0,320,0, time cost: 0.014s
Generating 40, 196,5895-34615-0000,0,332,0, time cost: 0.014s
Generating 41, 57,2035-147960-0001,0,391,0, time cost: 0.017s
Generating 42, 232,6295-244435-0024,0,418,0, time cost: 0.017s
Generating 43, 150,3536-23268-0015,0,393,0, time cost: 0.017s
Generating 44, 129,2803-154320-0002,0,351,0, time cost: 0.017s
Generating 45, 172,3752-4943-0026,0,403,0, time cost: 0.017s
Generating 46, 177,5338-24615-0009,0,424,0, time cost: 0.017s
Generating 47, 134,2803-154320-0008,0,357,0, time cost: 0.017s
Generating 48, 246,6313-66125-0014,0,377,0, time cost: 0.017s
Generating 49, 290,7976-105575-0009,0,403,0, time cost: 0.017s
Generating 50, 178,5338-24615-0010,0,387,0, time cost: 0.017s
Generating 51, 283,652-129742-0017,0,339,0, time cost: 0.017s
Generating 52, 257,6319-275224-0012,0,410,0, time cost: 0.017s
Generating 53, 149,3536-23268-0014,0,348,0, time cost: 0.017s
Generating 54, 321,84-121123-0001,0,397,0, time cost: 0.017s
Generating 55, 312,8297-275154-0017,0,368,0, time cost: 0.017s
Generating 56, 281,652-129742-0014,0,393,0, time cost: 0.017s
Generating 57, 66,2035-147960-0012,0,424,0, time cost: 0.017s
Generating 58, 162,3752-4943-0012,0,338,0, time cost: 0.017s
Generating 59, 63,2035-147960-0009,0,348,0, time cost: 0.017s
Generating 60, 35,1988-147956-0005,0,345,0, time cost: 0.017s
Generating 61, 235,6295-244435-0034,0,340,0, time cost: 0.017s
Generating 62, 126,251-118436-0021,0,396,0, time cost: 0.017s
Generating 63, 264,6345-64257-0010,0,397,0, time cost: 0.017s
Generating 64, 136,2803-154320-0011,0,426,0, time cost: 0.017s
Generating 65, 308,8297-275154-0008,0,402,0, time cost: 0.017s
Generating 66, 301,7976-105575-0026,0,353,0, time cost: 0.017s
Generating 67, 115,251-118436-0001,0,371,0, time cost: 0.017s
Generating 68, 135,2803-154320-0010,0,399,0, time cost: 0.017s
Generating 69, 140,2902-9006-0004,0,378,0, time cost: 0.017s
Generating 70, 217,6241-61943-0009,0,383,0, time cost: 0.017s
Generating 71, 214,6241-61943-0004,0,339,0, time cost: 0.017s
Generating 72, 141,2902-9006-0006,0,398,0, time cost: 0.017s
Generating 73, 316,8297-275154-0024,0,365,0, time cost: 0.017s
Generating 74, 277,652-129742-0010,0,338,0, time cost: 0.017s
Generating 75, 218,6241-61943-0011,0,388,0, time cost: 0.017s
Generating 76, 42,1988-147956-0018,0,352,0, time cost: 0.017s
Generating 77, 189,5694-64025-0007,0,390,0, time cost: 0.017s
Generating 78, 331,84-121123-0018,0,353,0, time cost: 0.017s
Generating 79, 60,2035-147960-0004,0,415,0, time cost: 0.017s
Generating 80, 160,3752-4943-0009,0,358,0, time cost: 0.017s
Generating 81, 157,3752-4943-0003,0,623,0, time cost: 0.031s
Generating 82, 48,1993-147149-0000,0,670,0, time cost: 0.031s
Generating 83, 41,1988-147956-0017,0,628,0, time cost: 0.031s
Generating 84, 273,652-129742-0004,0,710,0, time cost: 0.031s
Generating 85, 302,7976-105575-0027,0,666,0, time cost: 0.031s
Generating 86, 27,174-168635-0006,0,655,0, time cost: 0.031s
Generating 87, 43,1988-147956-0020,0,676,0, time cost: 0.031s
Generating 88, 293,7976-105575-0014,0,747,0, time cost: 0.031s
Generating 89, 110,2428-83699-0037,0,638,0, time cost: 0.031s
Generating 90, 341,8842-302196-0009,0,704,0, time cost: 0.031s
Generating 91, 44,1988-147956-0022,0,752,0, time cost: 0.034s
Generating 92, 208,5895-34615-0019,0,684,0, time cost: 0.034s
Generating 93, 207,5895-34615-0017,0,734,0, time cost: 0.034s
Generating 94, 71,2277-149874-0003,0,768,0, time cost: 0.034s
Generating 95, 198,5895-34615-0003,0,659,0, time cost: 0.034s
Generating 96, 225,6241-61943-0024,0,734,0, time cost: 0.034s
Generating 97, 237,6295-244435-0036,0,720,0, time cost: 0.034s
Generating 98, 327,84-121123-0008,0,700,0, time cost: 0.034s
Generating 99, 75,2277-149874-0010,0,740,0, time cost: 0.034s
Generating 100, 270,6345-64257-0019,0,770,0, time cost: 0.034s
Generating 101, 256,6319-275224-0010,0,692,0, time cost: 0.029s
Generating 102, 83,2277-149874-0020,0,736,0, time cost: 0.029s
Generating 103, 336,8842-302196-0002,0,664,0, time cost: 0.029s
Generating 104, 122,251-118436-0014,0,667,0, time cost: 0.029s
Generating 105, 191,5694-64025-0011,0,701,0, time cost: 0.029s
Generating 106, 14,1462-170138-0013,0,700,0, time cost: 0.029s
Generating 107, 114,2428-83699-0042,0,641,0, time cost: 0.029s
Generating 108, 289,7976-105575-0008,0,717,0, time cost: 0.029s
Generating 109, 119,251-118436-0008,0,621,0, time cost: 0.029s
Generating 110, 8,1272-128104-0013,0,708,0, time cost: 0.029s
Generating 111, 305,8297-275154-0004,0,664,0, time cost: 0.033s
Generating 112, 116,251-118436-0002,0,695,0, time cost: 0.033s
Generating 113, 210,6241-61943-0000,0,693,0, time cost: 0.033s
Generating 114, 61,2035-147960-0005,0,657,0, time cost: 0.033s
Generating 115, 322,84-121123-0003,0,678,0, time cost: 0.033s
Generating 116, 87,2412-153947-0002,0,658,0, time cost: 0.033s
Generating 117, 45,1988-147956-0026,0,690,0, time cost: 0.033s
Generating 118, 334,84-121123-0025,0,624,0, time cost: 0.033s
Generating 119, 152,3536-23268-0018,0,757,0, time cost: 0.033s
Generating 120, 72,2277-149874-0005,0,635,0, time cost: 0.033s
Generating 121, 206,5895-34615-0014,0,514,0, time cost: 0.024s
Generating 122, 161,3752-4943-0010,0,506,0, time cost: 0.024s
Generating 123, 0,1272-128104-0000,0,584,0, time cost: 0.024s
Generating 124, 77,2277-149874-0012,0,506,0, time cost: 0.024s
Generating 125, 325,84-121123-0006,0,560,0, time cost: 0.024s
Generating 126, 6,1272-128104-0010,0,558,0, time cost: 0.024s
Generating 127, 4,1272-128104-0006,0,562,0, time cost: 0.024s
Generating 128, 299,7976-105575-0022,0,536,0, time cost: 0.024s
Generating 129, 280,652-129742-0013,0,558,0, time cost: 0.024s
Generating 130, 247,6313-66125-0017,0,505,0, time cost: 0.024s
Generating 131, 169,3752-4943-0022,0,518,0, time cost: 0.025s
Generating 132, 231,6295-244435-0018,0,531,0, time cost: 0.025s
Generating 133, 163,3752-4943-0013,0,552,0, time cost: 0.025s
Generating 134, 288,7976-105575-0005,0,554,0, time cost: 0.025s
Generating 135, 342,8842-302196-0012,0,561,0, time cost: 0.025s
Generating 136, 219,6241-61943-0012,0,584,0, time cost: 0.025s
Generating 137, 37,1988-147956-0009,0,514,0, time cost: 0.025s
Generating 138, 16,1462-170138-0017,0,619,0, time cost: 0.025s
Generating 139, 337,8842-302196-0004,0,572,0, time cost: 0.025s
Generating 140, 339,8842-302196-0007,0,620,0, time cost: 0.025s
Generating 141, 59,2035-147960-0003,0,582,0, time cost: 0.024s
Generating 142, 263,6345-64257-0004,0,603,0, time cost: 0.024s
Generating 143, 36,1988-147956-0007,0,585,0, time cost: 0.024s
Generating 144, 252,6313-66125-0025,0,530,0, time cost: 0.024s
Generating 145, 340,8842-302196-0008,0,529,0, time cost: 0.024s
Generating 146, 118,251-118436-0005,0,529,0, time cost: 0.024s
Generating 147, 97,2428-83699-0007,0,569,0, time cost: 0.024s
Generating 148, 74,2277-149874-0008,0,537,0, time cost: 0.024s
Generating 149, 186,5536-43358-0015,0,594,0, time cost: 0.024s
Generating 150, 260,6319-275224-0019,0,576,0, time cost: 0.024s
Generating 151, 221,6241-61943-0017,0,607,0, time cost: 0.028s
Generating 152, 139,2803-154320-0014,0,527,0, time cost: 0.028s
Generating 153, 192,5694-64025-0015,0,505,0, time cost: 0.028s
Generating 154, 47,1988-147956-0028,0,586,0, time cost: 0.028s
Generating 155, 96,2412-153947-0016,0,517,0, time cost: 0.028s
Generating 156, 171,3752-4943-0024,0,564,0, time cost: 0.028s
Generating 157, 17,1462-170138-0022,0,617,0, time cost: 0.028s
Generating 158, 284,652-129742-0018,0,546,0, time cost: 0.028s
Generating 159, 267,6345-64257-0016,0,576,0, time cost: 0.028s
Generating 160, 292,7976-105575-0012,0,514,0, time cost: 0.028s
Generating 161, 183,5536-43358-0010,0,812,0, time cost: 0.042s
Generating 162, 203,5895-34615-0010,0,775,0, time cost: 0.042s
Generating 163, 209,5895-34615-0020,0,951,0, time cost: 0.042s
Generating 164, 31,174-168635-0019,0,798,0, time cost: 0.042s
Generating 165, 88,2412-153947-0004,0,870,0, time cost: 0.042s
Generating 166, 250,6313-66125-0023,0,933,0, time cost: 0.042s
Generating 167, 91,2412-153947-0009,0,870,0, time cost: 0.042s
Generating 168, 64,2035-147960-0010,0,957,0, time cost: 0.042s
Generating 169, 28,174-168635-0012,0,834,0, time cost: 0.042s
Generating 170, 155,3752-4943-0000,0,881,0, time cost: 0.042s
Generating 171, 104,2428-83699-0025,0,799,0, time cost: 0.038s
Generating 172, 153,3536-23268-0026,0,881,0, time cost: 0.038s
Generating 173, 272,652-129742-0001,0,864,0, time cost: 0.038s
Generating 174, 319,8297-275154-0027,0,873,0, time cost: 0.038s
Generating 175, 5,1272-128104-0007,0,922,0, time cost: 0.038s
Generating 176, 18,1462-170138-0023,0,948,0, time cost: 0.038s
Generating 177, 34,1988-147956-0004,0,901,0, time cost: 0.038s
Generating 178, 181,5536-43358-0007,0,940,0, time cost: 0.038s
Generating 179, 195,5694-64025-0019,0,885,0, time cost: 0.038s
Generating 180, 112,2428-83699-0040,0,781,0, time cost: 0.038s
Generating 181, 58,2035-147960-0002,0,882,0, time cost: 0.037s
Generating 182, 279,652-129742-0012,0,927,0, time cost: 0.037s
Generating 183, 147,3536-23268-0007,0,919,0, time cost: 0.037s
Generating 184, 108,2428-83699-0034,0,810,0, time cost: 0.037s
Generating 185, 262,6345-64257-0003,0,876,0, time cost: 0.037s
Generating 186, 120,251-118436-0009,0,894,0, time cost: 0.037s
Generating 187, 82,2277-149874-0019,0,843,0, time cost: 0.037s
Generating 188, 230,6295-244435-0017,0,853,0, time cost: 0.037s
Generating 189, 79,2277-149874-0014,0,858,0, time cost: 0.037s
Generating 190, 228,6295-244435-0009,0,825,0, time cost: 0.037s
Generating 191, 274,652-129742-0006,0,910,0, time cost: 0.038s
Generating 192, 46,1988-147956-0027,0,771,0, time cost: 0.038s
Generating 193, 21,1673-143396-0002,0,783,0, time cost: 0.038s
Generating 194, 90,2412-153947-0007,0,872,0, time cost: 0.038s
Generating 195, 3,1272-128104-0005,0,899,0, time cost: 0.038s
Generating 196, 123,251-118436-0016,0,895,0, time cost: 0.038s
Generating 197, 213,6241-61943-0003,0,781,0, time cost: 0.038s
Generating 198, 49,1993-147149-0001,0,952,0, time cost: 0.038s
Generating 199, 13,1462-170138-0010,0,860,0, time cost: 0.038s
Generating 200, 56,2035-147960-0000,0,900,0, time cost: 0.038s
Generating 201, 269,6345-64257-0018,0,477,0, time cost: 0.020s
Generating 202, 215,6241-61943-0005,0,488,0, time cost: 0.020s
Generating 203, 314,8297-275154-0020,0,445,0, time cost: 0.020s
Generating 204, 243,6313-66125-0007,0,491,0, time cost: 0.020s
Generating 205, 81,2277-149874-0018,0,500,0, time cost: 0.020s
Generating 206, 333,84-121123-0023,0,467,0, time cost: 0.020s
Generating 207, 179,5338-24615-0012,0,428,0, time cost: 0.020s
Generating 208, 148,3536-23268-0009,0,430,0, time cost: 0.020s
Generating 209, 20,1462-170138-0027,0,499,0, time cost: 0.020s
Generating 210, 32,174-168635-0022,0,432,0, time cost: 0.020s
Generating 211, 234,6295-244435-0031,0,473,0, time cost: 0.024s
Generating 212, 318,8297-275154-0026,0,487,0, time cost: 0.024s
Generating 213, 307,8297-275154-0007,0,447,0, time cost: 0.024s
Generating 214, 80,2277-149874-0015,0,471,0, time cost: 0.024s
Generating 215, 275,652-129742-0007,0,487,0, time cost: 0.024s
Generating 216, 317,8297-275154-0025,0,486,0, time cost: 0.024s
Generating 217, 102,2428-83699-0020,0,487,0, time cost: 0.024s
Generating 218, 240,6313-66125-0003,0,456,0, time cost: 0.024s
Generating 219, 109,2428-83699-0036,0,458,0, time cost: 0.024s
Generating 220, 38,1988-147956-0012,0,455,0, time cost: 0.024s
Generating 221, 205,5895-34615-0013,0,473,0, time cost: 0.020s
Generating 222, 251,6313-66125-0024,0,439,0, time cost: 0.020s
Generating 223, 224,6241-61943-0023,0,434,0, time cost: 0.020s
Generating 224, 65,2035-147960-0011,0,436,0, time cost: 0.020s
Generating 225, 323,84-121123-0004,0,438,0, time cost: 0.020s
Generating 226, 101,2428-83699-0019,0,489,0, time cost: 0.020s
Generating 227, 258,6319-275224-0013,0,485,0, time cost: 0.020s
Generating 228, 131,2803-154320-0005,0,475,0, time cost: 0.020s
Generating 229, 138,2803-154320-0013,0,435,0, time cost: 0.020s
Generating 230, 168,3752-4943-0020,0,486,0, time cost: 0.020s
Generating 231, 70,2035-147960-0016,0,488,0, time cost: 0.020s
Generating 232, 133,2803-154320-0007,0,449,0, time cost: 0.020s
Generating 233, 29,174-168635-0014,0,481,0, time cost: 0.020s
Generating 234, 298,7976-105575-0021,0,464,0, time cost: 0.020s
Generating 235, 291,7976-105575-0010,0,451,0, time cost: 0.020s
Generating 236, 300,7976-105575-0023,0,476,0, time cost: 0.020s
Generating 237, 296,7976-105575-0018,0,427,0, time cost: 0.020s
Generating 238, 249,6313-66125-0021,0,496,0, time cost: 0.020s
Generating 239, 68,2035-147960-0014,0,445,0, time cost: 0.020s
Generating 240, 188,5694-64025-0003,0,490,0, time cost: 0.020s
Generating 241, 146,3536-23268-0002,0,1048,0, time cost: 0.059s
Generating 242, 95,2412-153947-0015,0,1101,0, time cost: 0.059s
Generating 243, 303,8297-275154-0000,0,1020,0, time cost: 0.059s
Generating 244, 261,6319-275224-0020,0,1192,0, time cost: 0.059s
Generating 245, 145,2902-9006-0019,0,1421,0, time cost: 0.059s
Generating 246, 173,5338-24615-0000,0,1001,0, time cost: 0.059s
Generating 247, 158,3752-4943-0004,0,1399,0, time cost: 0.059s
Generating 248, 127,2803-154320-0000,0,1146,0, time cost: 0.059s
Generating 249, 180,5536-43358-0006,0,1039,0, time cost: 0.059s
Generating 250, 1,1272-128104-0002,0,1247,0, time cost: 0.059s
Generating 251, 185,5536-43358-0013,0,1038,0, time cost: 0.058s
Generating 252, 304,8297-275154-0002,0,974,0, time cost: 0.058s
Generating 253, 187,5694-64025-0002,0,1094,0, time cost: 0.058s
Generating 254, 137,2803-154320-0012,0,979,0, time cost: 0.058s
Generating 255, 156,3752-4943-0001,0,1106,0, time cost: 0.058s
Generating 256, 154,3536-23268-0027,0,1030,0, time cost: 0.058s
Generating 257, 294,7976-105575-0016,0,1019,0, time cost: 0.058s
Generating 258, 89,2412-153947-0006,0,1166,0, time cost: 0.058s
Generating 259, 143,2902-9006-0009,0,1195,0, time cost: 0.058s
Generating 260, 33,1988-147956-0001,0,1419,0, time cost: 0.058s
Generating 261, 276,652-129742-0009,0,1395,0, time cost: 0.058s
Generating 262, 130,2803-154320-0004,0,1199,0, time cost: 0.058s
Generating 263, 26,174-168635-0004,0,1275,0, time cost: 0.058s
Generating 264, 2,1272-128104-0003,0,988,0, time cost: 0.058s
Generating 265, 94,2412-153947-0014,0,1278,0, time cost: 0.058s
Generating 266, 282,652-129742-0015,0,1179,0, time cost: 0.058s
Generating 267, 254,6319-275224-0001,0,1216,0, time cost: 0.058s
Generating 268, 117,251-118436-0003,0,1100,0, time cost: 0.058s
Generating 269, 54,1993-147149-0028,0,1015,0, time cost: 0.058s
Generating 270, 142,2902-9006-0008,0,1106,0, time cost: 0.058s
Generating 271, 259,6319-275224-0014,0,1071,0, time cost: 0.054s
Generating 272, 176,5338-24615-0007,0,1006,0, time cost: 0.054s
Generating 273, 125,251-118436-0019,0,1146,0, time cost: 0.054s
Generating 274, 12,1462-170138-0005,0,1315,0, time cost: 0.054s
Generating 275, 229,6295-244435-0016,0,1149,0, time cost: 0.054s
Generating 276, 193,5694-64025-0016,0,1070,0, time cost: 0.054s
Generating 277, 151,3536-23268-0016,0,1130,0, time cost: 0.054s
Generating 278, 92,2412-153947-0011,0,1011,0, time cost: 0.054s
Generating 279, 204,5895-34615-0012,0,1032,0, time cost: 0.054s
Generating 280, 227,6295-244435-0004,0,1230,0, time cost: 0.054s
Generating 281, 132,2803-154320-0006,0,216,0, time cost: 0.016s
Generating 282, 285,652-129742-0019,0,277,0, time cost: 0.016s
Generating 283, 320,84-121123-0000,0,207,0, time cost: 0.016s
Generating 284, 233,6295-244435-0027,0,240,0, time cost: 0.016s
Generating 285, 100,2428-83699-0014,0,220,0, time cost: 0.016s
Generating 286, 306,8297-275154-0005,0,276,0, time cost: 0.016s
Generating 287, 73,2277-149874-0006,0,273,0, time cost: 0.016s
Generating 288, 295,7976-105575-0017,0,192,0, time cost: 0.016s
Generating 289, 244,6313-66125-0009,0,269,0, time cost: 0.016s
Generating 290, 111,2428-83699-0039,0,196,0, time cost: 0.016s
Generating 291, 238,6313-66125-0000,0,234,0, time cost: 0.011s
Generating 292, 245,6313-66125-0012,0,227,0, time cost: 0.011s
Generating 293, 315,8297-275154-0023,0,258,0, time cost: 0.011s
Generating 294, 166,3752-4943-0017,0,226,0, time cost: 0.011s
Generating 295, 85,2412-153947-0000,0,253,0, time cost: 0.011s
Generating 296, 332,84-121123-0022,0,259,0, time cost: 0.011s
Generating 297, 202,5895-34615-0009,0,276,0, time cost: 0.011s
Generating 298, 19,1462-170138-0026,0,237,0, time cost: 0.011s
Generating 299, 69,2035-147960-0015,0,154,0, time cost: 0.011s
Generating 300, 9,1272-128104-0014,0,223,0, time cost: 0.011s
Generating 301, 93,2412-153947-0012,0,196,0, time cost: 0.011s
Generating 302, 103,2428-83699-0021,0,280,0, time cost: 0.011s
Generating 303, 200,5895-34615-0006,0,251,0, time cost: 0.011s
Generating 304, 212,6241-61943-0002,0,272,0, time cost: 0.011s
Generating 305, 223,6241-61943-0021,0,250,0, time cost: 0.011s
Generating 306, 165,3752-4943-0016,0,247,0, time cost: 0.011s
Generating 307, 326,84-121123-0007,0,198,0, time cost: 0.011s
Generating 308, 297,7976-105575-0020,0,207,0, time cost: 0.011s
Generating 309, 113,2428-83699-0041,0,205,0, time cost: 0.011s
Generating 310, 216,6241-61943-0007,0,262,0, time cost: 0.011s
Generating 311, 11,1462-170138-0003,0,230,0, time cost: 0.011s
Generating 312, 40,1988-147956-0014,0,217,0, time cost: 0.011s
Generating 313, 286,7976-105575-0001,0,278,0, time cost: 0.011s
Generating 314, 328,84-121123-0013,0,238,0, time cost: 0.011s
Generating 315, 194,5694-64025-0018,0,267,0, time cost: 0.011s
Generating 316, 220,6241-61943-0015,0,247,0, time cost: 0.011s
Generating 317, 76,2277-149874-0011,0,245,0, time cost: 0.011s
Generating 318, 167,3752-4943-0019,0,248,0, time cost: 0.011s
Generating 319, 313,8297-275154-0018,0,219,0, time cost: 0.011s
Generating 320, 67,2035-147960-0013,0,266,0, time cost: 0.011s
Generating 321, 10,1462-170138-0000,0,1453,0, time cost: 0.130s
Generating 322, 324,84-121123-0005,0,1594,0, time cost: 0.130s
Generating 323, 335,8842-302196-0000,0,1463,0, time cost: 0.130s
Generating 324, 144,2902-9006-0018,0,3203,0, time cost: 0.130s
Generating 325, 253,6313-66125-0027,0,1445,0, time cost: 0.130s
Generating 326, 182,5536-43358-0008,0,2037,0, time cost: 0.130s
Generating 327, 128,2803-154320-0001,0,1554,0, time cost: 0.130s
Generating 328, 175,5338-24615-0005,0,1775,0, time cost: 0.130s
Generating 329, 24,1673-143396-0012,0,1445,0, time cost: 0.130s
Generating 330, 199,5895-34615-0004,0,1593,0, time cost: 0.130s
Generating 331, 55,1993-147149-0030,0,1550,0, time cost: 0.093s
Generating 332, 255,6319-275224-0008,0,1843,0, time cost: 0.093s
Generating 333, 25,1673-143396-0016,0,1444,0, time cost: 0.093s
Generating 334, 50,1993-147149-0003,0,1428,0, time cost: 0.093s
Generating 335, 53,1993-147149-0022,0,1652,0, time cost: 0.093s
Generating 336, 23,1673-143396-0009,0,1644,0, time cost: 0.093s
Generating 337, 338,8842-302196-0005,0,2343,0, time cost: 0.093s
Generating 338, 310,8297-275154-0014,0,1807,0, time cost: 0.093s
Generating 339, 190,5694-64025-0010,0,2160,0, time cost: 0.093s
Generating 340, 7,1272-128104-0011,0,1510,0, time cost: 0.093s
local/vc/am_pytorch/01_gen.sh: line 58: 80718 Segmentation fault      (core dumped) python ${proj_dir}/main.py --inference --module-config ${config_file} --cudnn-deterministic-toggle --batch-size ${batch_size} --num-workers ${batch_size} --sampler block_shuffle_by_length --cudnn-benchmark-toggle --ignore-cached-file-infor --output-dir ${output_dir} --trained-model ${TEMP_ACOUSTIC_NETWORK_PATH}










* Links

Dieses README
/data/work3/cgeng/Voice-Privacy-Challenge-2022/nii_scripts/waveform-modeling/project-WaveNet/README


sidekit: https://projets-lium.univ-lemans.fr/sidekit/index.html
